### ISSUE TITLE
Migration fails due to "duplicate" document and exporter crashes due to missing checksum

### ISSUE THREAD

**Issue by evils** [danielquinn/paperless#105]
I've updated Paperless today via git. As part of the upgrade process I used `./manage.py migrate` to migrate the database. As with Issue #97 a checksum has been introduced to the DB to make sure the same document won't get imported twice.

Now during the migrate process, paperless was calculating checksum's for my documents and apparently there was a duplicate (even though I highly doubt that it was a duplicate as they should be two different documents if something didn't go wrong initially).
So migrate gave me the following output:

```
    * Generating a checksum for 20160330145803-zahnarzt.tiff
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/root/.local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/root/.local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/root/.local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/root/.local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/root/.local/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/paperless/paperless/src/documents/migrations/0014_document_checksum.py", line 120, in set_checksums
    raise RuntimeError(error)
RuntimeError: 

================================================================================
It appears that you have two identical documents in your collection and 
Paperless no longer supports this (see issue #97).  The documents in question
are:

  * 20160330145757-versicherung.tiff (id: 24)
  * 20160330145803-zahnarzt.tiff (id: 23)

To fix this problem, you'll have to remove one of them from the database, a task
most easily done by running the following command in the same
directory as manage.py:

  $ echo 'DELETE FROM documents_document WHERE id = 23;' | ./manage.py dbshell

When that's finished, re-run the migrate, and provided that there aren't any
other duplicates, you should be good to go.
================================================================================
```

For sure I didn't run the suggested dbshell instruction as I definitely don't want to delete a document I believe isn't a duplicate and important to me. So I tried to export it before deleting it to make sure this isn't a duplicate or so. So I ran the exporter that then crashed like this:

```
[root@secondary-pi2 src]# ./manage.py document_exporter /root/export/
Traceback (most recent call last):
  File "/root/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: documents_document.checksum

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/paperless/paperless/src/documents/management/commands/document_exporter.py", line 53, in handle
    self.dump()
  File "/home/paperless/paperless/src/documents/management/commands/document_exporter.py", line 58, in dump
    document_map = {d.pk: d for d in documents}
  File "/root/.local/lib/python3.5/site-packages/django/db/models/query.py", line 258, in __iter__
    self._fetch_all()
  File "/root/.local/lib/python3.5/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/root/.local/lib/python3.5/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/root/.local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/root/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/root/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/root/.local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/.local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/root/.local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: documents_document.checksum
```

I'm now stuck with a Database that can't/won't be read by the web interface and my documents somewhere encrypted :)
I do believe the two documents in question are not identical (although I know how hashes work ...) as these documents were documents I had to split manually and reupload due to a scanning a scanning error.

It'd be great if I could export the documents to see if they are duplicates and then eventually clean the DB to run migrate!

Thanks

**Comment by danielquinn** [comment]
I was worried that something like this would happen, so I did lots and lots of testing, but obviously I missed something and I'm sorry about that.  Here's a quick fix that should get you going to do your export.

1. Open `documents/models.py`
2. Modify the `Document` class and comment out the `checksum` definition (lines 160-167)
3. Run `./manage.py document_exporter`  Ignore any messages about as-yet-run migrations as that's the one that's failing for you.

That *should* get you sorted.  If not, reply here and I'll see what I can do for you.

As for what's going wrong, it's hard to know from here.  I in fact had a duplicate in my own database when I first installed the update, but that was indeed a duplicate (there appears to be a problem with the mail consumer duplicating imports, but I haven't figured out where it's coming from yet).  If indeed you've managed to generate the same checksum with different files, then you've managed to find a collision in md5 -- not impossible obviously, but I thought that it was *improbable* enough to go with it.  If you can reproduce this, then I may have to write an update that switches everything to sha256 just to be safe.

So, once your export is done, please run the following on the exported files:

```bash
cat /path/to/file1.tiff | md5sum
cat /path/to/file2.tiff | md5sum
```

If they come out with the same checksum (and you've visibly confirmed that they're not just the same file with different names).  Please report back here and I'll add this sha256 change to my stack (or you can submit a PR!)

**Comment by evils** [comment]
I was able to export the files in question. Thanks a lot for the quick response and there's really no need to apologise for that! If you'd know how much better things work since I'm using your system, you'd demand money from me :dollar: 

It needs a while to download the files as my internet connection is pretty slow, I'll let you know what caused these duplicates in a few.

**Comment by danielquinn** [comment]
Ha!  Well so long as you're cool debugging this with me, I'll help where I can.  Just know that It's 2200h over there so I'll be going to bed soon, so if I don't respond right away, you may have to wait 'till morning or sometime later tomorrow.

**Comment by evils** [comment]
@danielquinn 
Now it's time for me to apologise that I might have doubted your implementation :disappointed: 
Your implementation works correctly, I failed when I manually splitted my scans and both tiffs are identical! I fixed my stuff and things are working!

Thanks a lot for all your help (again)

**Comment by danielquinn** [comment]
[Breathes a sigh of relief]  I'm glad it worked out.  I was worried that I somehow boned all of my users, so this is the best possible outcome.  And don't worry about it, I was hacking away on Paperless when your message came in anyway ;-)
