### ISSUE TITLE
First consumption-run: immediate error (Ubuntu-based OS)

### ISSUE THREAD

**Issue by sschnug** [danielquinn/paperless#111]
Hi, this lib looks amazing.

After installing all requirements and setting up (all according to docs; no dedicated/extra venv; python 3.5.1 anaconda-based), the following error is observed when i put my first test-pdf into the consumption-dir:

```python
Starting document consumer at *****
Consuming *****.pdf
Generating greyscale image from *****.pdf
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/XXX/miniconda2/envs/py3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/XXX/miniconda2/envs/py3/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/XXX/temo/paperless/src/documents/consumer.py", line 377, in run_unpaper
    (unpaper, pnm, pnm.replace(".pnm", ".unpaper.pnm"))).wait()
  File "/home/XXX/miniconda2/envs/py3/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/home/XXX/miniconda2/envs/py3/lib/python3.5/subprocess.py", line 1544, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'unpaper'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/XXX/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/XXX/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/XXX/.local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/XXX/.local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/XXX/temo/paperless/src/documents/management/commands/document_consumer.py", line 55, in handle
    self.loop()
  File "/home/XXX/temo/paperless/src/documents/management/commands/document_consumer.py", line 65, in loop
    self.file_consumer.consume()
  File "/home/XXX/temo/paperless/src/documents/consumer.py", line 124, in consume
    imgs = self._get_greyscale(tempdir, doc)
  File "/home/XXX/temo/paperless/src/documents/consumer.py", line 175, in _get_greyscale
    pool.map(run_unpaper, itertools.product([self.UNPAPER], pnms))
  File "/home/XXX/miniconda2/envs/py3/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/XXX/miniconda2/envs/py3/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
FileNotFoundError: [Errno 2] No such file or directory: 'unpaper'

```
An excerpt of my python-environment (i may have skipped some dependencies, but if they are in requirements, then they are installed!):
```
args                      0.1.0                     <pip>
cycler                    0.10.0                   py35_0    defaults
decorator                 4.0.9                    py35_0    defaults
dill                      0.2.5                     <pip>
django                    1.9.4                     <pip>
django-crispy-forms       1.6.0                     <pip>
django-extensions         1.6.1                     <pip>
django-filter             0.12.0                    <pip>
djangorestframework       3.3.2                     <pip>
filemagic                 1.6                       <pip>
flask                     0.10.1                   py35_1    defaults
fontconfig                2.11.1                        5    defaults
freetype                  2.5.5                         0    defaults
itsdangerous              0.24                     py35_0    defaults
jbig                      2.1                           0    defaults
jinja2                    2.8                      py35_0    defaults
jpeg                      8d                            0    defaults
langdetect                1.0.5                     <pip>
libpng                    1.6.17                        0    defaults
libtiff                   4.0.6                         1    defaults
libxml2                   2.9.2                         0    defaults
multiprocess              0.70.4                    <pip>
openssl                   1.0.2g                        0    defaults
pillow                    3.1.1                    py35_0    defaults
ptyprocess                0.5.1                     <pip>
pydicom                   0.9.9                     <pip>
pyocr                     0.3.1                     <pip>
python                    3.5.1                         0    defaults
python-gnupg              0.3.8                     <pip>
```

Before debugging this myself, i though i would post an issue and look if someone got an idea.
The only non-standard deviation from other setups may be the anaconda-based python distribution.
Thanks!

**Comment by danielquinn** [comment]
Well with an error like that, my first question is: "do you have unpaper installed"?  If you're using ubuntu, it should be available with something as simple as `apt-get install unpaper`.

**Comment by sschnug** [comment]
Well, this is embarassing. Somehow i always put unpaper and paperless in the same box (don't know why). Maybe there there could be some test for the existence of the executables, but well... my bad.

Thanks!

**Comment by danielquinn** [comment]
That's a good suggestion.  I just added an issue for it.
