### ISSUE TITLE
Docker - Error on consume

### ISSUE THREAD

**Issue by pyle** [danielquinn/paperless#119]
Hey all,

Just setting up my instance of paperless using docker and I'm getting a couple of errors.
Primarily I'm having is with the consume function.
I have dropped a couple of pdf documents into the `/consume` directory, it starts detecting the document with no issues, then produces the following stack trace:

```
5/1/2016 6:48:04 PMStarting document consumer at /consume
5/1/2016 6:48:04 PMSkipping /consume/Doucment 2016-04-24 16-29-15.pdf as it appears to be a duplicate
5/1/2016 6:48:04 PMSkipping /consume/Doucment 2016-05-01 16-28-12.pdf as it appears to be a duplicate
5/1/2016 6:49:45 PMConsuming /consume/Program1042_Courses_Domestic.pdf
5/1/2016 6:49:45 PMGenerating greyscale image from /consume/Program1042_Courses_Domestic.pdf
5/1/2016 6:49:55 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0000.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0000.unpaper.pnm
5/1/2016 6:49:55 PMout of deviation range - NO ROTATING
5/1/2016 6:49:56 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0006.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0006.unpaper.pnm
5/1/2016 6:49:57 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0004.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0004.unpaper.pnm
5/1/2016 6:49:58 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0007.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0007.unpaper.pnm
5/1/2016 6:49:58 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0002.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0002.unpaper.pnm
5/1/2016 6:50:00 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0003.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0003.unpaper.pnm
5/1/2016 6:50:01 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0008.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0008.unpaper.pnm
5/1/2016 6:50:01 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0005.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0005.unpaper.pnm
5/1/2016 6:50:02 PMProcessing sheet #1: /tmp/paperless/paperlessj7y5kqnx/convert-0001.pnm -> /tmp/paperless/paperlessj7y5kqnx/convert-0001.unpaper.pnm
5/1/2016 6:50:02 PMout of deviation range - NO ROTATING
5/1/2016 6:50:02 PMGenerating the thumbnail
5/1/2016 6:50:07 PMOCRing the document
5/1/2016 6:50:07 PMParsing for eng
5/1/2016 6:50:17 PMParsing for eng
5/1/2016 6:50:29 PMParsing for eng
5/1/2016 6:50:39 PMTraceback (most recent call last):
5/1/2016 6:50:39 PM  File "/usr/src/paperless/src/manage.py", line 18, in <module>
5/1/2016 6:50:39 PM    execute_from_command_line(sys.argv)
5/1/2016 6:50:39 PM  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
5/1/2016 6:50:39 PM    utility.execute()
5/1/2016 6:50:39 PM  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
5/1/2016 6:50:39 PM    self.fetch_command(subcommand).run_from_argv(self.argv)
5/1/2016 6:50:39 PM  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
5/1/2016 6:50:39 PM    self.execute(*args, **cmd_options)
5/1/2016 6:50:39 PM  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
5/1/2016 6:50:39 PM    output = self.handle(*args, **options)
5/1/2016 6:50:39 PM  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 55, in handle
5/1/2016 6:50:39 PM    self.loop()
5/1/2016 6:50:39 PM  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 65, in loop
5/1/2016 6:50:39 PM    self.file_consumer.consume()
5/1/2016 6:50:39 PM  File "/usr/src/paperless/src/documents/consumer.py", line 129, in consume
5/1/2016 6:50:39 PM    document = self._store(self._get_ocr(imgs), doc, thumbnail)
5/1/2016 6:50:39 PM  File "/usr/src/paperless/src/documents/consumer.py", line 316, in _store
5/1/2016 6:50:39 PM    with open(document.source_path, "wb") as encrypted:
5/1/2016 6:50:39 PMFileNotFoundError: [Errno 2] No such file or directory: '/usr/src/paperless/src/../media/documents/originals/0000003.pdf.gpg'
```

Setup details:
Docker image: [pitkley/paperless](https://hub.docker.com/r/pitkley/paperless/)
All ENV variables are set as per the docs.
Docker 1.10.3
Docker managed using Kubernetes (but this should be an issue, the container still pulls and runs from the same image)

Notes:
I also change the paperless passphrase to a simple upper/lower case string but get the same issue.
Permissions on directories are set correctly.

Any comments/hints would be greatly appreciated 😄

**Comment by pitkley** [comment]
Have you host-mounted any directories? The error indicates that either the `media/documents` or the `media/documents/originals` directory is missing. If you have host-mounted the `media` directory and not created the directory tree as it is [here](https://github.com/danielquinn/paperless/tree/master/media/), this error pops.

**Comment by pyle** [comment]
That was it. Thanks @pitkley 😄 
I only had a blank media directory mounted. It automatically created the documents folder but not the originals and thumbnails folders below.

I've got another issue relating to the web server now. It doesn't start and the logs say it's stuck at reading the package list.

```
5/1/2016 7:50:21 PMMapping UID and GID for paperless:paperless to 1000:1000
5/1/2016 7:50:22 PMGet:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
5/1/2016 7:50:24 PMIgn http://httpredir.debian.org jessie InRelease
5/1/2016 7:50:24 PMGet:2 http://httpredir.debian.org jessie-updates InRelease [142 kB]
5/1/2016 7:50:24 PMGet:3 http://security.debian.org jessie/updates/main amd64 Packages [295 kB]
5/1/2016 7:50:25 PMGet:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
5/1/2016 7:50:25 PMGet:5 http://httpredir.debian.org jessie Release [148 kB]
5/1/2016 7:50:26 PMGet:6 http://httpredir.debian.org jessie-updates/main amd64 Packages [9283 B]
5/1/2016 7:50:27 PMGet:7 http://httpredir.debian.org jessie/main amd64 Packages [9034 kB]
5/1/2016 7:50:41 PMFetched 9694 kB in 19s (502 kB/s)
5/1/2016 7:50:43 PMReading package lists...
```

Should I create a separate issue for this one ? 

I started a fresh container on my desktop and it does the same thing. I can, however, run the command manually using a different port and it finds the packages no issue. i.e `runserver 0.0.0.0:8001`.

**Comment by pyle** [comment]
Actually @pitkley , not to worry. I found my issue. Have a dodgy port forward going on :) 
This can be closed now thanks.

**Comment by pitkley** [comment]
@pyle Cool, glad you got it working! 👍
