### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by tonio67** [danielquinn/paperless#153]
Hello

I wanted to install Paperless today. I followed the documentation on ReadTheDocs. I installed the requirements. But when I would initialise the database with `./manage.py migrate` I have this error.

`root@riesling:/home/paperless/src# ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python3.4/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/paperless/src/paperless/settings.py", line 15, in <module>
    from dotenv import load_dotenv
ImportError: cannot import name 'load_dotenv'`

Can anyone help me please?

tonio67

**Comment by pitkley** [comment]
If you have installed the requirements using

```console
$ pip install --user --requirement /path/to/paperless/requirements.txt
```

your issue might be that `pip` is linked to a Python 2 installation, while Paperless is running on Python 3. Try using the `pip3` instead:

```console
$ pip3 install --user --requirement /path/to/paperless/requirements.txt
```

**Comment by danielquinn** [comment]
Also if you can, make sure you're using a virtualenv, so the ambiguities of pip vs pip3 stop being a problem.

If the requirements were installed correctly ,the output of `pip3 freeze` should include `python-dotenv`.

**Comment by tonio67** [comment]
Thank you for your answers!
I did that : `pip install --user --requirement requirements.txt && pip3 install --user --requirement requirements.txt`
I have succeeded in launch everything. As I installed Paperless on a VM, I try to configure apache2 to enter there with my domain. Someone would have any idea ?

**Comment by danielquinn** [comment]
For Apache configurations, you should check out the [documentation](https://paperless.readthedocs.io/en/latest/setup.html#apache) as a section for Apache was just added a few weeks ago.
