### ISSUE TITLE
update broke paperless

### ISSUE THREAD

**Issue by Ulli2k** [danielquinn/paperless#175]
Yesterday I did an update on paperless and now it is not longer working.
I did

    cd /opt/paperless/
    git pull
    pip3 install --upgrade -r requirements.txt
    ./src/manage.py migrate

and got the following error on the migration command.

    ./src/manage.py migrate
    Traceback (most recent call last):
      File "./src/manage.py", line 18, in <module>
        execute_from_command_line(sys.argv)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
        utility.execute()
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 359, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 294, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 342, in execute
        self.check()
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 374, in check
        include_deployment_checks=include_deployment_checks,
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
        issues.extend(super(Command, self)._run_checks(**kwargs))
      File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 361, in _run_checks
        return checks.run_checks(**kwargs)
      File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
        new_errors = check(app_configs=app_configs)
      File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
        return check_resolver(resolver)
      File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
        for pattern in resolver.url_patterns:
      File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
        patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
      File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
        return import_module(self.urlconf_name)
      File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
      File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
      File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 1129, in _exec
      File "<frozen importlib._bootstrap>", line 1471, in exec_module
      File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
      File "/opt/paperless/src/paperless/urls.py", line 23, in <module>
        from documents.views import (
      File "/opt/paperless/src/documents/views.py", line 16, in <module>
        from .filters import DocumentFilterSet, CorrespondentFilterSet, TagFilterSet
      File "/opt/paperless/src/documents/filters.py", line 15, in <module>
        class RelatedFilter(django_filters.MethodFilter):
    AttributeError: 'module' object has no attribute 'MethodFilter'

**Comment by danielquinn** [comment]
Interesting.  That's not happenning to me with my own instance.  Can you any of these commands without it exploding?

* `./manage.py runserver`
* `./manage.py shell`
* `./manage.py shell_plus`

?

(Also, I hope you don't mind, but I edited your post to fix the formatting of the traceback.)

**Comment by Ulli2k** [comment]
> Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x414f7c90>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.4/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.4/dist-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.4/dist-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/paperless/src/paperless/urls.py", line 23, in <module>
    from documents.views import (
  File "/opt/paperless/src/documents/views.py", line 16, in <module>
    from .filters import DocumentFilterSet, CorrespondentFilterSet, TagFilterSet
  File "/opt/paperless/src/documents/filters.py", line 15, in <module>
    class RelatedFilter(django_filters.MethodFilter):
AttributeError: 'module' object has no attribute 'MethodFilter'

**Comment by danielquinn** [comment]
That's really weird, but I have a theory.  Maybe your local copy has some old .pyc files that are somehow not being cleaned up.  Do me a favour and try this:

First let me know that you are in fact running on `master`:

    $ git branch

There should be a green asterisk `*` next to `master`.  Next, check to make sure you haven't edited any files locally so I can be sure that the code you have is the code I have:

    $ git status

You shouldn't see any modified files in the output.

Lastly, if those both check out, just delete all .pyc files in the directory and try to re-run the runserver.  First try this:

    $ ./manage.py clean_pyc

and if that fails too, just do it the hard way:

    $ rm -rf $(find . -name '*.pyc' && find . -name '__pycache__')

Once you've tried all of that, let me know what happens.

**Comment by Ulli2k** [comment]
> root@DiskStation:/opt/paperless# git branch
> * master
> root@DiskStation:/opt/paperless# git status
> On branch master
> Your branch is behind 'origin/master' by 17 commits, and can be fast-forwarded.
>   (use "git pull" to update your local branch)
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
> 	modified:   src/paperless/settings.py
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> root@DiskStation:/opt/paperless# ./src/manage.py clean_pyc
> root@DiskStation:/opt/paperless#


./src/manage.py migrate <--still fails

**Comment by danielquinn** [comment]
Well that appears to be the problem:

> Your branch is behind 'origin/master' by 17 commits, and can be fast-forwarded.

What happens when you do `git pull`?

**Comment by danielquinn** [comment]
Also, if you've edited `settings.py`, please let me know how/why so I can make it more configurable.  You shouldn't have to edit that file.

**Comment by Ulli2k** [comment]
ahh, solved! THANKS
it is the old settings.py.
I changed the following values

> 		OCR_LANGUAGE = "deu"
> 		ALLOWED_HOSTS = ['diskstation']

**Comment by danielquinn** [comment]
Hooray!

I've since modified `ALLOWED_HOSTS` to use `"*"`, so that edit shouldn't be necessary, but you're right, `OCR_LANGUAGE=` is a glaring oversight on my part.  I'll have to make that configurable.  I'll open an issue for that and close this one.  Sound good?

**Comment by Ulli2k** [comment]
sounds awesome!

By the way mayan is bu...sh..t because it does not support automatic tagging or autosetting correspondents.
Thats the big issue on all of the CMS I have seen on the internet. And from my point of view thats the most important function.
