### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'message'

### ISSUE THREAD

**Issue by F13** [danielquinn/paperless#187]
Not really sure how to even begin debugging this one. I noticed not all documents in my folder were getting consumed. I manually ran the consumer, which happily added one document, and then didn't add any more. When I went to go look at the output from the consumer, this is what I was greeted with.

```
root@Paperless:/var/opt/paperless/src# ./manage.py document_consumer
Starting document consumer at /documents
Consuming /documents/20160313 - 004.pdf
Generating greyscale image from /documents/20160313 - 004.pdf
Processing sheet #1: /tmp/paperless/paperless28fsj7gz/convert-0000.pnm -> /tmp/p                                                                                                                             aperless/paperless28fsj7gz/convert-0000.unpaper.pnm
Processing sheet #1: /tmp/paperless/paperless28fsj7gz/convert-0001.pnm -> /tmp/p                                                                                                                             aperless/paperless28fsj7gz/convert-0001.unpaper.pnm
[image2 @ 0x9d1440] Encoder did not produce proper pts, making some up.
[image2 @ 0x1a60440] Encoder did not produce proper pts, making some up.
Generating the thumbnail
OCRing the document
Parsing for eng
Too few characters. Skipping this page
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/var/opt/paperless/src/documents/consumer.py", line 380, in image_to_str                                                                                                                             ing
    orientation = ocr.detect_orientation(f, lang=lang)
  File "/root/.local/lib/python3.5/site-packages/pyocr/libtesseract/__init__.py"                                                                                                                             , line 46, in detect_orientation
    os = tesseract_raw.detect_os(handle)
  File "/root/.local/lib/python3.5/site-packages/pyocr/libtesseract/tesseract_ra                                                                                                                             w.py", line 509, in detect_os
    raise TesseractError("TessBaseAPIDetectOS() failed")
TypeError: __init__() missing 1 required positional argument: 'message'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/__init__                                                                                                                             .py", line 367, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.5/site-packages/django/core/management/__init__                                                                                                                             .py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/base.py"                                                                                                                             , line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/.local/lib/python3.5/site-packages/django/core/management/base.py"                                                                                                                             , line 345, in execute
    output = self.handle(*args, **options)
  File "/var/opt/paperless/src/documents/management/commands/document_consumer.p                                                                                                                             y", line 56, in handle
    self.loop()
  File "/var/opt/paperless/src/documents/management/commands/document_consumer.p                                                                                                                             y", line 66, in loop
    self.file_consumer.consume()
  File "/var/opt/paperless/src/documents/consumer.py", line 128, in consume
    document = self._store(self._get_ocr(imgs), doc, thumbnail)
  File "/var/opt/paperless/src/documents/consumer.py", line 227, in _get_ocr
    raw_text = self._ocr([imgs[middle]], self.DEFAULT_OCR_LANGUAGE)
  File "/var/opt/paperless/src/documents/consumer.py", line 285, in _ocr
    r = pool.map(image_to_string, itertools.product(imgs, [lang]))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
TypeError: __init__() missing 1 required positional argument: 'message'
```

**Comment by danielquinn** [comment]
There was an issue a while ago about `Too few characters. Skipping this page`, but that was resolved, so before I dig into this, can you confirm that you're running the latest from `master`?  Also, if you're willing to share the document in question, that'll make figuring this out easier.

**Comment by F13** [comment]
I did a pull before beginning my testing for the evening, but I did another just now to be sure. Here is the output of `git branch` and `git show`:

```
root@Paperless:/var/opt/paperless# git branch
* master
```
```
root@Paperless:/var/opt/paperless# git show
commit ca2a556259112874e41ea7a1c560991b8766ec1e
Merge: 701ef2f 7699a88
Author: Daniel Quinn <danielquinn@users.noreply.github.com>
Date:   Wed Feb 1 09:25:19 2017 +0000

    Merge pull request #186 from rhaamo/specify_static_dir_using_conf_file

    Be able to override static root using config file
```

Looking at the document, I can see it potentially causing a problem. I've uploaded it to our private keybase folder.

**Comment by danielquinn** [comment]
I'm sorry, but I don't use Keybase.  I tried it, found it to be more of a shiny wrapper around a still totally broken model that assumes people work like computers.  True to form, I created a new private key, lost it, and promptly stopped using Keybase :-)

So if you'd like to send me the file, you'll have to do it in a less-secure, but more user-friendly way (sorry): code at danielquinn dot org

**Comment by F13** [comment]
Shoot, really? That's a shame. This is such a perfect example of when it's useful!

The gist of the document is that it's white text on different full-color backgrounds. Also the document is scanned sideways. Thinking the incorrect direction could be the cause, I ran the consumer again with a different file. This one is black text on a white background. This also died, but in a new way:

```
Consuming /documents/20160313 - 005.pdf
Generating greyscale image from /documents/20160313 - 005.pdf
Processing sheet #1: /tmp/paperless/paperless39wj4ci7/convert-0000.pnm -> /tmp/paperless/paperless39wj4ci7/convert-0000.unpaper.pnm
Processing sheet #1: /tmp/paperless/paperless39wj4ci7/convert-0002.pnm -> /tmp/paperless/paperless39wj4ci7/convert-0002.unpaper.pnm
Processing sheet #1: /tmp/paperless/paperless39wj4ci7/convert-0001.pnm -> /tmp/paperless/paperless39wj4ci7/convert-0001.unpaper.pnm
[image2 @ 0x15c7ac0] Encoder did not produce proper pts, making some up.
[image2 @ 0x1247ac0] Encoder did not produce proper pts, making some up.
[image2 @ 0x16e8ac0] Encoder did not produce proper pts, making some up.
Generating the thumbnail
OCRing the document
Parsing for eng
Detected 293 diacritics
Parsing for spa
Error opening data file /usr/share/tesseract-ocr/tessdata/spa.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'spa'
Tesseract couldn't load any languages!
Error opening data file /usr/share/tesseract-ocr/tessdata/spa.traineddata
Error opening data file /usr/share/tesseract-ocr/tessdata/spa.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'spa'
Failed loading language 'spa'
Tesseract couldn't load any languages!
Tesseract couldn't load any languages!
AdaptedTemplates != NULL:Error:Assert failed:in file adaptmatch.cpp, line 190
AdaptedTemplates != NULL:Error:Assert failed:in file adaptmatch.cpp, line 190
AdaptedTemplates != NULL:Error:Assert failed:in file adaptmatch.cpp, line 190
```

The script is still running, but has hung at this point.

**Comment by danielquinn** [comment]
From the looks of that output, it sounds like the document is in Spanish (or at least, that's what the language detection library Paperless is using thinks).  Based on this information, We're calling Tesseract and telling it to use Spanish as its basis for OCR and Tesseract is complaining that it doesn't have any language files for Spanish.

I don't know what your setup is like, but most Linux distros have their own way of installing multiple language support for Tesseract -- usually in the form of separate `tesseract-spa` packages or something like that.   Try getting that setup correctly and you should be ok.

As for Keybase, yeah it's a nifty idea, but it's still too much of a pain in the ass to use it on a day-to-day basis.  This business of having to create a key and then copy it around to all of my devices using incantations to import the key into some running background thing just so I can send messages to people that don't know what encryption is let alone how to use it...  It's just not *easy* enough -- and I'm a software engineer with 17 years of experience.

Anyway, I can't reproduce the problem locally without a source file to make it go.  There's [a unit test in this project](https://github.com/danielquinn/paperless/blob/master/src/documents/tests/test_consumer.py#L368) that's supposed to account for just this situation, so if you can come up with a file that still breaks (and isn't private -- and hopefully not too big?) then I'd love to add it to the test suite.

**Comment by F13** [comment]
Well, part of the issue is the document _isn't_ in Spanish. Let me ask this clarifying question: Should Paperless work properly if a document in scanned in sideways, or is that unsupported? I don't necessarily expect it to be, so if the fix is "turn the document, stupid," that's perfectly reasonable :)

I'll see if I can recreate the original issue with a more public document.

I'd love to chat more about Keybase at some point. My impression is the exact opposite of yours, actually - I've been impressed with just _how_ easy it is, given the level of security. It's not perfect, of course, but your notion of transporting a key does seem a little off to me. Each device should have its own. Regardless, I don't want to derail the issue comments too far.

**Comment by danielquinn** [comment]
I have no idea if Paperless would work if scanned sideways, but I'm going to go out on a limb and guess: *no*.  The logic relevant the consumer follows is:

1. Convert the a `.pnm` format, cleaned up with `unpaper`
2. Attempt to OCR the file first page with `language=en` and capture the result
3. Send the result to a language detection library and capture the "detected" language
4. OCR the entire document using the language given by the language detector

So, if you're passing in sideways-oriented text, and that's somehow confusing the OCR library, then it's probably passing garbage to the detection code, which in then "guesses" that it must be Spanish -- some crazy how.  Maybe, if we can somehow determine the orientation of the document, we could incorporate some rotation code in there (it's just Imagemagick after all) but at the moment, I wouldn't know where to start to get that orientation detection working.

Regarding your notes on Keybase, I'm curious myself as I had no idea that there was a way to store multiple keys, or if even that sort of thing was *"normal"*.  I was under the impression that `key == identity` so the idea of storing different keys on different devices sounded wrong...  Honestly, the biggest barrier to adoption of this stuff is the gaps in understanding between people who use it and those who don't yet.

If you'd like to drop me an email to ask whatever questions you like, feel free, though my responses may come across frustrated and ranting :-/
