### ISSUE TITLE
Gnupg error in FreeBSD

### ISSUE THREAD

**Issue by rajil** [danielquinn/paperless#205]
I am trying to use Paperless in FreeBSD jail. The document appears in the website but it is not OCR'd. The error i get is :
```
$ ./manage.py document_consumer
Starting document consumer at /usr/home/vftp/scandump
Consuming /usr/home/vftp/scandump/Report_001972.pdf
Processing sheet: /tmp/paperless/paperlessy9u56rvw/convert-0001.pnm -> /tmp/paperless/paperlessy9u56rvw/convert-0001.unpaper.pnm
Processing sheet: /tmp/paperless/paperlessy9u56rvw/convert-0000.pnm -> /tmp/paperless/paperlessy9u56rvw/convert-0000.unpaper.pnm
out of deviation range - NO ROTATING
OCRing the document
Parsing for eng
Parsing for eng
Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/gnupg.py", line 861, in _read_response
    result.handle_status(keyword, value)
  File "/usr/local/lib/python3.5/site-packages/gnupg.py", line 592, in handle_status
    Verify.handle_status(self, key, value)
  File "/usr/local/lib/python3.5/site-packages/gnupg.py", line 314, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'WARNING'

Exception in thread Thread-16:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/site-packages/gnupg.py", line 861, in _read_response
    result.handle_status(keyword, value)
  File "/usr/local/lib/python3.5/site-packages/gnupg.py", line 592, in handle_status
    Verify.handle_status(self, key, value)
  File "/usr/local/lib/python3.5/site-packages/gnupg.py", line 314, in handle_status
    raise ValueError("Unknown status message: %r" % key)
ValueError: Unknown status message: 'WARNING'

Completed
Document 20170326225352: Report_001972 consumption finished

```

I have installed the following packages
```
# pip3 list
cffi (1.10.0)
click (6.7)
dateutils (0.6.6)
Django (1.10.6)
django-crispy-forms (1.6.1)
django-dotenv (1.4.1)
django-extensions (1.7.7)
django-filter (1.0.2)
django-filters (0.2.1)
django-flat-responsive (1.3.0)
djangorestframework (3.6.2)
djangorestframework-extras (0.1)
dotenv (0.0.5)
img2pdf (0.2.3)
langdetect (1.0.7)
ocrmypdf (4.5.2)
olefile (0.44)
Pillow (3.4.2)
pip (8.1.1)
py-dotenv (0.1)
pycparser (2.17)
pyocr (0.4.6)
PyPDF2 (1.26.0)
python-dateutil (2.6.0)
python-dotenv (0.6.3)
python-gnupg (0.4.0)
python-magic (0.4.13)
pytz (2016.10)
reportlab (3.4.0)
ruffus (2.6.3)
setuptools (32.1.0)
six (1.10.0)
sqlite3 (0.0.0)
Tkinter (0.0.0)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
The gnupg package installed is
```
# pkg info |grep gnupg
gnupg-2.1.19                   The GNU Privacy Guard (modern version)
```

**Comment by danielquinn** [comment]
I'm sorry for the late reply on this, but I'm afraid I have no idea why GnuPG might be acting differently on a FreeBSD system, and since I don't have one myself, I have no way of testing for it.  If you figure out what's going wrong though, please feel free to issue a PR and I'll happily merge better FreeBSD support into the project.

**Comment by rajil** [comment]
I installed the following version of gnupg and now it works
```
#pkg info |grep gnupg
gnupg20-2.0.30_2               The GNU Privacy Guard (stable version)
```
