### ISSUE TITLE
Document consumer crashing when processing a .tiff file

### ISSUE THREAD

**Issue by kskyten** [danielquinn/paperless#244]
Something goes wrong with Tesseract when trying to process a `.tiff` file. I have paperless installed in the default Vagrant environment. I got the following error:
```shell
vagrant@dev:~$ /opt/paperless/src/manage.py document_consumer
Starting document consumer at /home/vagrant/consumption
Parsers available: RasterisedDocumentParser
Consuming /home/vagrant/consumption/foo.tiff
Processing sheet #1: /tmp/paperless/paperlessk9vq9xew/convert-0001.pnm -> /tmp/paperless/paperlessk9vq9xew/convert-0001.unpaper.pnm
Processing sheet #1: /tmp/paperless/paperlessk9vq9xew/convert-0000.pnm -> /tmp/paperless/paperlessk9vq9xew/convert-0000.unpaper.pnm
OCRing the document
Parsing for eng
Parsing for eng
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 214, in image_to_string
    return ocr.image_to_string(f, lang=lang)
  File "/usr/local/lib/python3.4/dist-packages/pyocr/tesseract.py", line 358, in image_to_string
    raise TesseractError(status, errors)
pyocr.error.TesseractError: (-9, b'Tesseract Open Source OCR Engine v3.03 with Leptonica\n')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/paperless/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/opt/paperless/src/documents/management/commands/document_consumer.py", line 57, in handle
    self.loop()
  File "/opt/paperless/src/documents/management/commands/document_consumer.py", line 67, in loop
    self.file_consumer.consume()
  File "/opt/paperless/src/documents/consumer.py", line 124, in consume
    parsed_document.get_text(),
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 55, in get_text
    return self._get_ocr(images)
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 131, in _get_ocr
    raw_text = self._assemble_ocr_sections(imgs, middle, raw_text)
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 174, in _assemble_ocr_sections
    text = self._ocr(imgs[:middle], self.DEFAULT_OCR_LANGUAGE) + text
  File "/opt/paperless/src/paperless_tesseract/parsers.py", line 163, in _ocr
    r = pool.map(image_to_string, itertools.product(imgs, [lang]))
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 599, in get
    raise self._value
pyocr.error.TesseractError: (-9, b'Tesseract Open Source OCR Engine v3.03 with Leptonica\n')
```

Running Tesseract directly on the file works.

**Comment by ddddavidmartin** [comment]
I remember @jmgilman having a similar issue before where it was due to not enough memory in the container environment. Have a look at https://github.com/openpaperwork/pyocr/issues/69, maybe it helps.

**Comment by kskyten** [comment]
Indeed, adding memory fixed the problem.
