### ISSUE TITLE
Skipping ... as it appears to be a duplicate

### ISSUE THREAD

**Issue by tomtme** [danielquinn/paperless#260]
I have recently used a new scanner to scan multiple files. Every file I'm getting this message or a different one stating that it can't find any images. I've updated just today, using the same config/data files but I seem to be having the same issues.

What can I do to help narrow down what is happening here?

**Comment by danielquinn** [comment]
For starters, a complete copy/paste of the error message of what's going on will help me understand just what kind of error is coming up.  Note that the consumption process can generate a number of warnings while it's converting the pdf to an image, so what you're seeing might actually be a warning and not a problem.

The `as it appears to be a duplicate` message comes up when Paperless hashes the file and compares that hash to those already in the database.  It's not an error, just a warning to let you know that it's not going to try and re-import something that looks like it's already in the database.

**Comment by ddddavidmartin** [comment]
Also, Paperless won't delete files that appear to be duplicates. You will have to remove it manually from the consumption directory [0].

[0] `PAPERLESS_CONSUMPTION_DIR` as set in your `paperless.conf`

**Comment by tomtme** [comment]
Ok. I've got a bit more time to investigate some more. Thanks for the quick reply.

It looks like they are added, but something is going wrong. I'm going to add a new  unique file -- or remove it if it exists. And just have that single file in the directory. Hopefully this will tell me/us what is going on here.

**Comment by tomtme** [comment]
So it looks like all is going well, then it just goes crazy and crashes.

`paperless@paperless:~$ /home/paperless/paperless2/src/manage.py document_consumer
Starting document consumer at /mnt/paperless.in
Parsers available: RasterisedDocumentParser
Consuming /mnt/paperless.in/a01011401.PDF
Processing sheet #1: /tmp/paperless/paperless1i0w5j6_/convert-0001.pnm -> /tmp/paperless/paperless1i0w5j6_/convert-0001.unpaper.pnm
Processing sheet #1: /tmp/paperless/paperless1i0w5j6_/convert-0000.pnm -> /tmp/paperless/paperless1i0w5j6_/convert-0000.unpaper.pnm
[image2 @ 0x564d56be84e0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x564d56be84e0] Encoder did not produce proper pts, making some up.
[image2 @ 0x55a875c154e0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x55a875c154e0] Encoder did not produce proper pts, making some up.
OCRing the document
Parsing for eng
Parsing for ces
Traceback (most recent call last):
  File "/home/paperless/paperless2/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/paperless/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/paperless/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/paperless/.local/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/paperless/.local/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/paperless/paperless2/src/documents/management/commands/document_consumer.py", line 57, in handle
    self.loop()
  File "/home/paperless/paperless2/src/documents/management/commands/document_consumer.py", line 67, in loop
    self.file_consumer.consume()
  File "/home/paperless/paperless2/src/documents/consumer.py", line 126, in consume
    thumbnail
  File "/home/paperless/paperless2/src/documents/consumer.py", line 199, in _store
    relevant_tags = set(list(Tag.match_all(text)) + list(file_info.tags))
  File "/home/paperless/paperless2/src/documents/models.py", line 77, in match_all
    if tag.matches(text):
  File "/home/paperless/paperless2/src/documents/models.py", line 111, in matches
    re.compile(self.match, **search_kwargs), text))
  File "/usr/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
`

**Comment by tomtme** [comment]
Looks like the file is listed, but not actually showing anything being there. It reports the gpg file is missing if I attempt to open it:
`Environment:


Request Method: GET
Request URL: http://localhost:9080/fetch/doc/1036

Django Version: 1.10.8
Python Version: 3.5.3
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'documents.apps.DocumentsConfig',
 'reminders.apps.RemindersConfig',
 'paperless_tesseract.apps.PaperlessTesseractConfig',
 'flat_responsive',
 'django.contrib.admin',
 'rest_framework',
 'crispy_forms',
 'django_filters']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/home/paperless/.local/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/home/paperless/.local/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/paperless/.local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/paperless/.local/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/paperless/.local/lib/python3.5/site-packages/django/views/generic/base.py" in view
  68.             return self.dispatch(request, *args, **kwargs)

File "/home/paperless/paperless2/src/paperless/mixins.py" in dispatch
  23.                 request, *args, **kwargs

File "/home/paperless/.local/lib/python3.5/site-packages/django/views/generic/base.py" in dispatch
  88.         return handler(request, *args, **kwargs)

File "/home/paperless/.local/lib/python3.5/site-packages/django/views/generic/detail.py" in get
  117.         return self.render_to_response(context)

File "/home/paperless/paperless2/src/documents/views.py" in render_to_response
  67.             GnuPG.decrypted(self.object.source_file),

File "/home/paperless/paperless2/src/documents/models.py" in source_file
  237.         return open(self.source_path, "rb")

Exception Type: FileNotFoundError at /fetch/doc/1036
Exception Value: [Errno 2] No such file or directory: '/mnt/paperless/documents/originals/0001036.pdf.gpg'
`

**Comment by danielquinn** [comment]
I'm not sure about the second error (missing gpg) but the first one looks like the regex you've got for either a `Correspondent` or `Tag`.  It looks like Paperless is trying to compile the regular expression you've entered and it's barfing on it.

I suggest that you change all of your tags and correspondents to use the `Any` matching algorithm until you get this sorted.  Then, re-add them one at a time until you find the one that's exploding.  Post it here and I'll see if I can help you.

The second error might be related to the first, as it's possible that since the consumer failed mid-process, the database record was created whilst not actually moving the file.  It's hard to be sure from here.  At the very least, this is a good reason for me to go back in there and wrap this whole process in a transaction.

The second error is just complaining that the original document isn't where it's supposed to be.  Normally, this is *very weird* but if you've been tinkering with files here and there to try and figure out what's happening, that might be the cause.

Alright, I'm going to create two separate issues to help make the code more resiliant in cases like this and I'll reference this issue for background.

**Comment by tomtme** [comment]
Sorry about the delay. It looks like you were correct. I had a * regex when I intended to have a .* regex to mark new unsorted entries. 

After resolving that I was able to clear the backlog. I appreciate your time in resolving this!
