### ISSUE TITLE
Can't download imported documents

### ISSUE THREAD

**Issue by Cludch** [danielquinn/paperless#332]
Hey,

I finally managed to import almost all of my previously exported documents using the `document_importer`, which I then pointed to the directory containing the .pdf files, thumbnails and the `manifest.json`. However, only 3 out of 100 documents show the thumbnail and these are the only ones I can download. If I try to download a document, which fails to show the thumbnail, I am facing the error `[Errno 2] No such file or directory: '/usr/src/paperless/src/../media/documents/originals/0000043.pdf.gpg'`.

Any idea what causes this or how this could be fixed?

And another question I have: My documents are named like this after the export `20121116142353-cludch-title`, but after importing them, the name stays the same and the title from the `manifest.json` is not used.

Edit: I just saw that my consumer is throwing the following error:
```
OCRing the document
Parsing for eng
Parsing for deu
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 85, in handle
    self.loop(mail_delta=mail_delta)
  File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 105, in loop
    self.file_consumer.run()
  File "/usr/src/paperless/src/documents/consumer.py", line 123, in run
    date = parsed_document.get_date()
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 209, in get_date
    text = self.get_text()
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 80, in get_text
    self._text = self._get_ocr(images)
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 161, in _get_ocr
    return self._ocr(imgs, ISO639[guessed_language])
  File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 186, in _ocr
    self.log("info", "Parsing for {}".format(lang))
  File "/usr/src/paperless/src/documents/parsers.py", line 46, in log
    "group": self.logging_group
  File "/usr/lib/python3.6/logging/__init__.py", line 1306, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/usr/src/paperless/src/documents/loggers.py", line 23, in emit
    Log.objects.create(**kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/src/paperless/src/documents/models.py", line 319, in save
    models.Model.save(self, *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/usr/lib/python3.6/site-packages/django/db/transaction.py", line 223, in __exit__
    connection.commit()
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 262, in commit
    self._commit()
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
  File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/django/db/backends/base/base.py", line 236, in _commit
    return self.connection.commit()
django.db.utils.OperationalError: database is locked
```

**Comment by danielquinn** [comment]
That sounds like a lot of different problems stacked on top of each other, and they may not all be related.

As Paperless uses a Sqlite database, the complaint that it's locked could be due to more than one process trying to write to it -- which really shouldn't happen unless you're running two consumers in parallel?  That's a guess of course, but as I've never seen that error, I can only speculate.

As for your export/import woes, I'm afraid that without more information, it's really hard to know what's wrong. Just to check though, I just exported my entire collection, deleted the database and all the original files, and then imported everything and nothing broke.  Here's the commands I did to make that happen in case it helps:

```bash
$ cd /path/to/paperless/src/
$ ./manage.py document_exporter /tmp/paperless
$ cd ..
$ rm data/db.sqlite3 media/documents/*/*
$ cd src
$ ./manage.py migrate
$ ./manage.py createsuperuser
$ ./manage.py document_importer /tmp/paperless/
```

Finally, as part of my export/import test, I checked on the use of the `title` you mentioned.  Unfortunately, everything looks ok on this end: the title was pulled from `manifest.json` and stored in the database as the document title, and the files themselves were encrypted with GPG and stored in `media/originals/` with a name like `0000258.pdf.gpg`.

I'm sorry I can't be of much more help here, but maybe some of the above will point you in the right direction.
