### ISSUE TITLE
Consumer shuts down when malformated filename are present

### ISSUE THREAD

**Issue by Somebody25** [danielquinn/paperless#341]
Hello!

I am using paperless with docker and first of all, great project, I really like it!

I noticed, that if a malformated filename is present in the consumption directory, the consumer shuts down with exit code 1. No Log entry is present in the gui, so it is necessary to connect to the server and look in the docker logs to see whats wrong.

Examples of this behaviour:

Date in filename if of wrong format

```
consumer_1   | Consuming /consume/06112017Z - Tierklinik - Herzultraschall - tierarzt,rechnung.pdf
consumer_1   | convert: profile 'icc': 'RGB ': RGB color space not permitted on grayscale PNG '/tmp/paperless/paperless-loarf4yw/convert-%04d.png' @ warning/png.c/MagickPNGWarningHandler/1744.
consumer_1   | Skipping OCR, using Text from PDF
consumer_1   | Detected document date 2013-03-02T00:00:00+00:00 based on string 02.03.2013
consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/src/paperless/src/manage.py", line 18, in <module>
consumer_1   |     execute_from_command_line(sys.argv)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
consumer_1   |     utility.execute()
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
consumer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
consumer_1   |     self.execute(*args, **cmd_options)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
consumer_1   |     output = self.handle(*args, **options)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 85, in handle
consumer_1   |     self.loop(mail_delta=mail_delta)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 105, in loop
consumer_1   |     self.file_consumer.run()
consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 128, in run
consumer_1   |     date
consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 181, in _store
consumer_1   |     file_info = FileInfo.from_path(doc)
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 450, in from_path
consumer_1   |     cls._mangle_property(properties, "created")
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 432, in _mangle_property
consumer_1   |     properties[name]
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 397, in _get_created
consumer_1   |     return dateutil.parser.parse("{:0<14}Z".format(created[:-1]))
consumer_1   |   File "/usr/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1312, in parse
consumer_1   |     return DEFAULTPARSER.parse(timestr, **kwargs)
consumer_1   |   File "/usr/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 612, in parse
consumer_1   |     ret = self._build_naive(res, default)
consumer_1   |   File "/usr/lib/python3.6/site-packages/dateutil/parser/_parser.py", line 1188, in _build_naive
consumer_1   |     naive = default.replace(**repl)
consumer_1   | ValueError: month must be in 1..12
paperless_consumer_1 exited with code 1
```

File contains wrongly encoded character:
```
consumer_1   | Consuming /consume/20171023Z - Krank - Arbeitsunf\udce4higkeit - krank.pdf
consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
consumer_1   |     return super(CursorDebugWrapper, self).execute(sql, params)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1   |     return self.cursor.execute(sql, params)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
consumer_1   |     return Database.Cursor.execute(self, query, params)
consumer_1   | UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 56: surrogates not allowed
consumer_1   |
consumer_1   | During handling of the above exception, another exception occurred:
consumer_1   |
consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/src/paperless/src/manage.py", line 18, in <module>
consumer_1   |     execute_from_command_line(sys.argv)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
consumer_1   |     utility.execute()
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
consumer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
consumer_1   |     self.execute(*args, **cmd_options)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
consumer_1   |     output = self.handle(*args, **options)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 85, in handle
consumer_1   |     self.loop(mail_delta=mail_delta)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 105, in loop
consumer_1   |     self.file_consumer.run()
consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 111, in run
consumer_1   |     self.log("info", "Consuming {}".format(doc))
consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 73, in log
consumer_1   |     "group": self.logging_group
consumer_1   |   File "/usr/lib/python3.6/logging/__init__.py", line 1306, in info
consumer_1   |     self._log(INFO, msg, args, **kwargs)
consumer_1   |   File "/usr/lib/python3.6/logging/__init__.py", line 1442, in _log
consumer_1   |     self.handle(record)
consumer_1   |   File "/usr/lib/python3.6/logging/__init__.py", line 1452, in handle
consumer_1   |     self.callHandlers(record)
consumer_1   |   File "/usr/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
consumer_1   |     hdlr.handle(record)
consumer_1   |   File "/usr/lib/python3.6/logging/__init__.py", line 863, in handle
consumer_1   |     self.emit(record)
consumer_1   |   File "/usr/src/paperless/src/documents/loggers.py", line 23, in emit
consumer_1   |     Log.objects.create(**kwargs)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
consumer_1   |     obj.save(force_insert=True, using=self.db)
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 319, in save
consumer_1   |     models.Model.save(self, *args, **kwargs)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
consumer_1   |     force_update=force_update, update_fields=update_fields)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
consumer_1   |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
consumer_1   |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
consumer_1   |     using=using, raw=raw)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
consumer_1   |     return query.get_compiler(using=using).execute_sql(return_id)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1113, in execute_sql
consumer_1   |     cursor.execute(sql, params)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 83, in execute
consumer_1   |     sql = self.db.ops.last_executed_query(self.cursor, sql, params)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/sqlite3/operations.py", line 135, in last_executed_query
consumer_1   |     params = self._quote_params_for_last_executed_query(params)
consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/sqlite3/operations.py", line 124, in _quote_params_for_last_executed_query
consumer_1   |     return cursor.execute(sql, params).fetchone()
consumer_1   | UnicodeEncodeError: 'utf-8' codec can't encode character '\udce4' in position 56: surrogates not allowed
paperless_consumer_1 exited with code 1
```

For now I am setting the `restart: on-failure` in the docker-compose.yml but i fear that the consumer will just constantly start up and error out.

The behaviour I suggest would be to log the error like "month must be in 1..12" and if possible to shove the offending files in an error pipeline (maybe folder that can be given like the consumption folder) and try to continue consuming the not problamatic files. This would certanly reduce the need to connect to the server and look for issues and clean the consumption folder.

**Comment by danielquinn** [comment]
Thanks for reporting this -- I wonder how many people have had the consumer explode on them and given up.

The date error has now been fixed: 7223ea3c but I'm afraid I don't know what to do with that second error.  I've never seen that message before.  What was the file name in question exactly?  Paperless has been [tested](https://github.com/danielquinn/paperless/blob/master/src/documents/tests/test_consumer.py#L62-L360) against all kinds of file names (including non-ASCII ones) so I'm struggling to reproduce your problem in a unit test.

As for setting `restart: on-failure`, you're right.  The consumer will just try (and fail) to consume that file until you delete it, so we need to do more here.  I just don't know what the right fix is yet.

**Comment by ddddavidmartin** [comment]
I have recently seen the consumer seemingly stop in the middle of processing without any visible errors. Though in my case starting it again let it parse the file without issues so it may have been a different issue. I'll update my installation to the latest and keep an eye on it.

**Comment by Somebody25** [comment]
Ok, I found the issue.
I pulled the file from a cifs mounted filesystem. I was missing the `iocharset=utf8` attribute so the filenames were not correctly displayed. When I mount the filesystem correctly, I succeed in importing filenames with very complicated filenames such as `20180423Z - test - Cömplîcáteä Fílenäme - test.pdf`.

I will update my installation so that the date doesn't cause the consume to crash anymore.

**Comment by danielquinn** [comment]
Interesting!  Would you be willing to add a note to the [troubleshooting](https://github.com/danielquinn/paperless/blob/master/docs/troubleshooting.rst) section to the documentation about this?

**Comment by Strubbl** [comment]
It seems i also have a corrupt file, where the consumer dies. Currently i do not know how to work around this except modifying the pdf itself:

```
Apr 23 18:13:50 spence docker[28394]: Consuming /consume/20170920Z - Blablue - Zettel 09.2017 - blablue,oorbeit.pdf
Apr 23 18:14:16 spence docker[28394]: Processing sheet #1: /tmp/paperless/paperless-w1frfv8l/convert-0000.pnm -> /tmp/paperless/paperless-w1frfv8l/convert-0000.unpaper.pnm
Apr 23 18:14:16 spence docker[28394]: Processing sheet #1: /tmp/paperless/paperless-w1frfv8l/convert-0003.pnm -> /tmp/paperless/paperless-w1frfv8l/convert-0003.unpaper.pnm
Apr 23 18:14:16 spence docker[28394]: [pgm_pipe @ 0x5570f815b700] Stream #0: not enough frames to estimate rate; consider increasing probesize
Apr 23 18:14:16 spence docker[28394]: [pgm_pipe @ 0x56029d912700] Stream #0: not enough frames to estimate rate; consider increasing probesize
Apr 23 18:14:16 spence docker[28394]: Processing sheet #1: /tmp/paperless/paperless-w1frfv8l/convert-0002.pnm -> /tmp/paperless/paperless-w1frfv8l/convert-0002.unpaper.pnm
Apr 23 18:14:16 spence docker[28394]: Processing sheet #1: /tmp/paperless/paperless-w1frfv8l/convert-0001.pnm -> /tmp/paperless/paperless-w1frfv8l/convert-0001.unpaper.pnm
Apr 23 18:14:16 spence docker[28394]: [pgm_pipe @ 0x55da7c5b6700] Stream #0: not enough frames to estimate rate; consider increasing probesize
Apr 23 18:14:17 spence docker[28394]: [pgm_pipe @ 0x56526e5da700] Stream #0: not enough frames to estimate rate; consider increasing probesize
Apr 23 18:14:37 spence docker[28394]: [image2 @ 0x56526e5db720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Apr 23 18:14:37 spence docker[28394]: [image2 @ 0x56526e5db720] Encoder did not produce proper pts, making some up.
Apr 23 18:14:37 spence docker[28394]: out of deviation range - NO ROTATING
Apr 23 18:14:37 spence docker[28394]: Processing sheet #1: /tmp/paperless/paperless-w1frfv8l/convert-0004.pnm -> /tmp/paperless/paperless-w1frfv8l/convert-0004.unpaper.pnm
Apr 23 18:14:37 spence docker[28394]: [pgm_pipe @ 0x556468406700] Stream #0: not enough frames to estimate rate; consider increasing probesize
Apr 23 18:14:39 spence docker[28394]: [image2 @ 0x5570f815c720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Apr 23 18:14:39 spence docker[28394]: [image2 @ 0x5570f815c720] Encoder did not produce proper pts, making some up.
Apr 23 18:14:39 spence docker[28394]: Processing sheet #1: /tmp/paperless/paperless-w1frfv8l/convert-0005.pnm -> /tmp/paperless/paperless-w1frfv8l/convert-0005.unpaper.pnm
Apr 23 18:14:39 spence docker[28394]: [pgm_pipe @ 0x55bd1c86f700] Stream #0: not enough frames to estimate rate; consider increasing probesize
Apr 23 18:14:40 spence docker[28394]: [image2 @ 0x55da7c5b7720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Apr 23 18:14:40 spence docker[28394]: [image2 @ 0x55da7c5b7720] Encoder did not produce proper pts, making some up.
Apr 23 18:14:40 spence docker[28394]: Processing sheet #1: /tmp/paperless/paperless-w1frfv8l/convert-0006.pnm -> /tmp/paperless/paperless-w1frfv8l/convert-0006.unpaper.pnm
Apr 23 18:14:40 spence docker[28394]: [pgm_pipe @ 0x561d9f442700] Stream #0: not enough frames to estimate rate; consider increasing probesize
Apr 23 18:14:41 spence docker[28394]: [image2 @ 0x56029d913720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Apr 23 18:14:41 spence docker[28394]: [image2 @ 0x56029d913720] Encoder did not produce proper pts, making some up.
Apr 23 18:14:52 spence docker[28394]: [image2 @ 0x556468407720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Apr 23 18:14:52 spence docker[28394]: [image2 @ 0x556468407720] Encoder did not produce proper pts, making some up.
Apr 23 18:14:52 spence docker[28394]: out of deviation range - NO ROTATING
Apr 23 18:15:01 spence docker[28394]: [image2 @ 0x55bd1c870720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Apr 23 18:15:01 spence docker[28394]: [image2 @ 0x55bd1c870720] Encoder did not produce proper pts, making some up.
Apr 23 18:15:01 spence docker[28394]: out of deviation range - NO ROTATING
Apr 23 18:15:01 spence docker[28394]: [image2 @ 0x561d9f443720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Apr 23 18:15:01 spence docker[28394]: [image2 @ 0x561d9f443720] Encoder did not produce proper pts, making some up.
Apr 23 18:15:01 spence docker[28394]: OCRing the document
Apr 23 18:15:01 spence docker[28394]: Parsing for eng
Apr 23 18:15:23 spence docker[28394]: Parsing for deu
Apr 23 18:16:01 spence docker[28394]: multiprocessing.pool.RemoteTraceback:
Apr 23 18:16:01 spence docker[28394]: """
Apr 23 18:16:01 spence docker[28394]: Traceback (most recent call last):
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/site-packages/pyocr/tesseract.py", line 214, in detect_orientation
Apr 23 18:16:01 spence docker[28394]:     angle = int(output.get('Rotate', output['Orientation in degrees']))
Apr 23 18:16:01 spence docker[28394]: KeyError: 'Orientation in degrees'
Apr 23 18:16:01 spence docker[28394]: During handling of the above exception, another exception occurred:
Apr 23 18:16:01 spence docker[28394]: Traceback (most recent call last):
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
Apr 23 18:16:01 spence docker[28394]:     result = (True, func(*args, **kwds))
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
Apr 23 18:16:01 spence docker[28394]:     return list(map(*args))
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 286, in image_to_string
Apr 23 18:16:01 spence docker[28394]:     orientation = ocr.detect_orientation(f, lang=lang)
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/site-packages/pyocr/tesseract.py", line 224, in detect_orientation
Apr 23 18:16:01 spence docker[28394]:     % (ex.message, original_output))
Apr 23 18:16:01 spence docker[28394]: AttributeError: 'KeyError' object has no attribute 'message'
Apr 23 18:16:01 spence docker[28394]: """
Apr 23 18:16:01 spence docker[28394]: The above exception was the direct cause of the following exception:
Apr 23 18:16:01 spence docker[28394]: Traceback (most recent call last):
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/manage.py", line 18, in <module>
Apr 23 18:16:01 spence docker[28394]:     execute_from_command_line(sys.argv)
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
Apr 23 18:16:01 spence docker[28394]:     utility.execute()
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
Apr 23 18:16:01 spence docker[28394]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
Apr 23 18:16:01 spence docker[28394]:     self.execute(*args, **cmd_options)
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
Apr 23 18:16:01 spence docker[28394]:     output = self.handle(*args, **options)
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 85, in handle
Apr 23 18:16:01 spence docker[28394]:     self.loop(mail_delta=mail_delta)
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 105, in loop
Apr 23 18:16:01 spence docker[28394]:     self.file_consumer.run()
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/documents/consumer.py", line 123, in run
Apr 23 18:16:01 spence docker[28394]:     date = parsed_document.get_date()
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 209, in get_date
Apr 23 18:16:01 spence docker[28394]:     text = self.get_text()
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 80, in get_text
Apr 23 18:16:01 spence docker[28394]:     self._text = self._get_ocr(images)
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 161, in _get_ocr
Apr 23 18:16:01 spence docker[28394]:     return self._ocr(imgs, ISO639[guessed_language])
Apr 23 18:16:01 spence docker[28394]:   File "/usr/src/paperless/src/paperless_tesseract/parsers.py", line 189, in _ocr
Apr 23 18:16:01 spence docker[28394]:     r = pool.map(image_to_string, itertools.product(imgs, [lang]))
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/multiprocessing/pool.py", line 266, in map
Apr 23 18:16:01 spence docker[28394]:     return self._map_async(func, iterable, mapstar, chunksize).get()
Apr 23 18:16:01 spence docker[28394]:   File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
Apr 23 18:16:01 spence docker[28394]:     raise self._value
Apr 23 18:16:01 spence docker[28394]: AttributeError: 'KeyError' object has no attribute 'message'
Apr 23 18:16:02 spence systemd[1]: docker-container@strubbl-paperless-consumer.service: Main process exited, code=exited, status=1/FAILURE
```

i am running paperless master branch and the commit is b733b32c1d3794d99cf14b4795a6aaf6b4c0d69b. 
And i just pulled the latest commits to confirm the error exists with current HEAD commit 20a4a66a57ce867f7fab99bb632856d3d2f5ce22

**Comment by Strubbl** [comment]
Sorry, unfortunately i cannot share the file.

**Comment by danielquinn** [comment]
@Somebody25 if you do a `git pull`, do you still have this problem with dates in `DDMMYYYY` format?
@Strubbl I understand.  It's one of the annoying things about working on Paperless -- everyone's stuff is too secure to share :-)  The good news though is that your error appears to be related to #345 which I *just* patched this morning.  Please give that a shot and let me know if this helped.

**Comment by Strubbl** [comment]
@danielquinn  Yes, my issue is fixed. Thank you!

**Comment by danielquinn** [comment]
Hooray!

**Comment by Somebody25** [comment]
I can also confirm that the date issue is fixed.
Thank you!
