### ISSUE TITLE
Cannot start webserver on 2.2.0

### ISSUE THREAD

**Issue by kmlucy** [danielquinn/paperless#392]
When I try to start Paperless webserver in Docker with version 2.2.0, I get the following error and it doesn't start:

```
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 317, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python3.6/site-packages/django/conf/__init__.py", line 106, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/src/paperless/src/paperless/settings.py", line 102, in <module>
    MIDDLEWARE.remove("django.contrib.auth.middleware.SessionAuthenticationMiddleware")
ValueError: list.remove(x): x not in list
```

**Comment by danielquinn** [comment]
Yup, that was the problem.  We had a line in there explicitly removing `SessionAuthenticationMiddleware`, which as of Django 2.0, doesn't exist any more :-)  I've removed the line and now things appear to work logins disabled.  Just do a `git pull` and you should be working.

**Comment by kmlucy** [comment]
That fixed it. Thanks for the quick fix!
