### ISSUE TITLE
Exception when consuming document with tag matching in filename

### ISSUE THREAD

**Issue by boringusername99** [danielquinn/paperless#393]
I'm getting an exception when importing a particular document with multiple tags. Note: the tag I was attempting to apply has some personal information so I've made some minor substitutions.

Sidebar - I noticed that filename matching doesn't seem to work with tags that have spaces in them. That may be related to the current issue - I went through my tags removing spaces from all of them and moving to CamelCase.

**Taxes17 Tag**
Name: Taxes17
Slug: Taxes17 
Match: <blank>
Matching: any

**government Tag**
Name: government
Slug: government
Match: <blank>
Matching: any

**22MainSt Tag**
Name: 22MainSt
Slug: 22-main-st
Match: "main apartments","main st"
Matching: all

**Error message:**
```
Parsers available: RasterisedDocumentParser
Consuming /Volumes/Storage 2/Dropbox/scans-paperless_import/20170630Z - City of Nashua - 2016-2017 Property Tax Bill - Taxes17,22MainSt,government.pdf
Processing sheet #1: /tmp/paperless/paperless-gesm08z9/convert-0000.pnm -> /tmp/paperless/paperless-gesm08z9/convert-0000.unpaper.pnm
[pgm_pipe @ 0x7f7fdb807200] Stream #0: not enough frames to estimate rate; consider increasing probesize
[image2 @ 0x7f7fdb807800] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x7f7fdb807800] Encoder did not produce proper pts, making some up.
OCRing the document
Parsing for eng
Detected document date 2013-12-07T00:00:00-08:00 based on string 07-12-13
Traceback (most recent call last):
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/query.py", line 464, in get_or_create
    return self.get(**lookup), False
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/query.py", line 380, in get
    self.model._meta.object_name
documents.models.DoesNotExist: Tag matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: UNIQUE constraint failed: documents_tag.name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/myuser/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/myuser/paperless/src/documents/management/commands/document_consumer.py", line 100, in handle
    self.loop(loop_time, mail_delta)
  File "/Users/myuser/paperless/src/documents/management/commands/document_consumer.py", line 109, in loop
    self.loop_step(mail_delta, start_time)
  File "/Users/myuser/paperless/src/documents/management/commands/document_consumer.py", line 123, in loop_step
    self.file_consumer.consume_new_files()
  File "/Users/myuser/paperless/src/documents/consumer.py", line 111, in consume_new_files
    if not self.try_consume_file(file):
  File "/Users/myuser/paperless/src/documents/consumer.py", line 154, in try_consume_file
    date
  File "/Users/myuser/paperless/src/documents/consumer.py", line 203, in _store
    file_info = FileInfo.from_path(doc)
  File "/Users/myuser/paperless/src/documents/models.py", line 483, in from_path
    cls._mangle_property(properties, "tags")
  File "/Users/myuser/paperless/src/documents/models.py", line 462, in _mangle_property
    properties[name]
  File "/Users/myuser/paperless/src/documents/models.py", line 446, in _get_tags
    Tag.objects.get_or_create(slug=t, defaults={"name": t})[0])
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/query.py", line 466, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/query.py", line 506, in _create_object_from_params
    six.reraise(*exc_info)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/query.py", line 498, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/query.py", line 394, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/myuser/paperless/src/documents/models.py", line 150, in save
    models.Model.save(self, *args, **kwargs)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/base.py", line 924, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/base.py", line 963, in _do_insert
    using=using, raw=raw)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/query.py", line 1076, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1112, in execute_sql
    cursor.execute(sql, params)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/myuser/virtualenvs/paperless/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: UNIQUE constraint failed: documents_tag.name
```

**Comment by danielquinn** [comment]
Well Paperless shouldn't crash out like this, so it's definitely a bug, but I should point out that the `tag` you put in your file name isn't the *name*, but rather the *slug* of the tag.  A "slug" is the standard way of stripping names into something a little more url/filename/whatever safe.  It converts spaces to hyphens, lowercases everything, and strips non-ascii characters so `this is My Name` becomes `this-is-my-name`.  If you use slugs in your file name, it should work regardless of what the name of the tag is.

To get the slug of a tag, just open it in the admin and it should be printed out there.

**Comment by jonaswinkler** [comment]
The problem here is in models.py:375, calling `get_or_create(slug=t.lower(), defaults={"name": t})`.

Whenever a file is consumed and the filename contains tags as specified in [Guesswork](https://paperless.readthedocs.io/en/latest/guesswork.html), this thing is responsible for returning Tag objects. If no tag with a matching slug exists for a given tag t from the filename, a new tag will be created with slug=t and name=t. However, a tag with name t may already exist. This might happen if the user modifies the slug of tags manually.

https://docs.djangoproject.com/en/2.1/ref/models/querysets/#get-or-create

In this case, "22MainSt" is causing the issue, since "22MainSt".lower(), which is "22mainst", does not match the slug of any tag. Therefore, an attempt is made to create a new tag with name="22MainSt", which already exists. Bam.

**Comment by danielquinn** [comment]
Thanks for the analysis @jonaswinkler!  I'm afraid that the only way I could see to fix this is to impose a standard for tag names rather than allowing people to tinker with them.  To that end I've made the following changes:

1. Slugs are no longer editable.  They're derived from the name of the tag or correspondent at save time, so if you wanna change the slug, you have to change the name, and even then you're restricted to the rules of the `slugify()` function.  The slug value is still visible in the admin though.
2. I've added a migration to go over all existing tags & correspondents and rewrite the `.slug` values to ones conforming to the `slugify()` rules.
3. The consumption process now uses the same rules as `.save()` in determining a slug and using that to check for an existing tag/correspondent.

I'm pretty sure that this'll solve the problem, so I'm going to close this issue.  @boringusername99 if you still have problems on this front, let me know and I'll re-open to see what can be done.
