### ISSUE TITLE
OSError: dlopen(libc.so.6, 6): image not found on Mac OSX 10.11.5 - inotify related

### ISSUE THREAD

**Issue by boringusername99** [danielquinn/paperless#418]
I get this error when attempting to run the document consumer. Is inotify not supported/available on this version of OSX? If that's the case, how do I disable it?

```
(paperless) abcuser@Macpro ~/bin$ ./launch_paperless_document_consumer
Starting document consumer at /Volumes/Storage 2/Dropbox/scans-paperless_import with inotify
Traceback (most recent call last):
  File "/Users/abcuser/paperless/src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/abcuser/.virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/Users/abcuser/.virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/abcuser/.virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/abcuser/.virtualenvs/paperless/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "/Users/abcuser/paperless/src/documents/management/commands/document_consumer.py", line 96, in handle
    self.loop_inotify(mail_delta)
  File "/Users/abcuser/paperless/src/documents/management/commands/document_consumer.py", line 125, in loop_inotify
    inotify = INotify()
  File "/Users/abcuser/.virtualenvs/paperless/lib/python3.6/site-packages/inotify_simple/inotify_simple.py", line 86, in __init__
    _ensure_libc_loaded()
  File "/Users/abcuser/.virtualenvs/paperless/lib/python3.6/site-packages/inotify_simple/inotify_simple.py", line 60, in _ensure_libc_loaded
    _libc = ctypes.cdll.LoadLibrary('libc.so.6')
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libc.so.6, 6): image not found
```

**Comment by tompicking** [comment]
I see this issue is closed. However, I have the same error on Mac OSX. Is there a Linux-only restriction?

**Comment by erikarvstedt** [comment]
This error happens on macOS when the Python package `inotify_simple` is installed.
We prevent this by restricting the installation of this package to Linux in `requirements.txt`.

**Comment by erikarvstedt** [comment]
You're right, the Linux-only restriction was reverted by https://github.com/the-paperless-project/paperless/commit/9ab50ed09dd60893144d86afadd6279c1970dbf7.
I've added a new fix.

**Comment by dbaldy** [comment]
If that can help someone I had the same problem on OSX after a git pull. I solved it by manually uninstalling inotify-simple from the virtualenv  (`pip uninstall inotify-simple`) and the consumer runs fine now.
