### ISSUE TITLE
cross compilation in to PREFIX make paperless unable to find libmagic

### ISSUE THREAD

**Issue by nephaste** [danielquinn/paperless#436]
Hi Paperless team,

I am Qnap NAS integrator...
I've crosscompiled paperless into a prefix ( /opt/Paperless) with all dependency and Python included 
all passed well

but on start Paperless is  unable to find libmagic while exisiting within /opt/Paperless/lib/

`[/] # Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7ffa2e7158>
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/urls/resolvers.py", line 540, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/django/urls/resolvers.py", line 533, in urlconf_module
    return import_module(self.urlconf_name)
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/paperless/src/paperless/urls.py", line 9, in <module>
    from documents.views import (
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/paperless/src/documents/views.py", line 24, in <module>
    from .forms import UploadForm
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/paperless/src/documents/forms.py", line 1, in <module>
    import magic
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/magic/__init__.py", line 18, in <module>
    from magic.identify import Magic, MagicError
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/magic/identify.py", line 16, in <module>
    from magic import api
  File "/share/CACHEDEV1_DATA/.qpkg/PaperLess/lib/python3.7/site-packages/magic/api.py", line 22, in <module>
    raise ImportError('Unable to find magic library')
ImportError: Unable to find magic library
`
libmagic.so is well present... i used source from File-5 to get it

ftp://ftp.astron.com/pub/file/file-5.35.tar.gz

also tried to move file within /usr/lib for test but issue remain the same...

I wonder if you have a solution to bring me

**Comment by erikarvstedt** [comment]
What's the location of libmagic.so on your system?

**Comment by erikarvstedt** [comment]
You have to explicitly specify your special library path:
```
LD_LIBRARY_PATH="/opt/Paperless/lib/${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH" python /opt/Paperless/src/manage.py
```

**Comment by ovv** [comment]
This look like the failing line:
`libname = ctypes.util.find_library('magic') or ctypes.util.find_library('magic1')` [link](https://github.com/aliles/filemagic/blob/master/magic/api.py#L12)

This is what the documentation says about `find_library`

```
On Linux, find_library() tries to run external programs (/sbin/ldconfig, gcc, objdump and ld) to find the library file. It returns the filename of the library file.

Changed in version 3.6: On Linux, the value of the environment variable LD_LIBRARY_PATH is used when searching for libraries, if a library cannot be found by any other means.
```

Does `ctypes.util.find_library('magic') or ctypes.util.find_library('magic1')` works on system python ?

**Comment by nephaste** [comment]
create a test.py with those 3 lines

`[/share/CACHEDEV1_DATA/.qpkg/PaperLess/paperless/src] # vi test.py
[/share/CACHEDEV1_DATA/.qpkg/PaperLess/paperless/src] # /opt/PaperLess/bin/python3 test.py
None
None
`

**Comment by nephaste** [comment]
`LD_LIBRARY_PATH=/opt/PaperLess/lib:$LD_LIBRARY_PATH /opt/PaperLess/bin/python3 test.py`

[/share/CACHEDEV1_DATA/.qpkg/PaperLess/paperless/src] # ls /opt/PaperLess/lib/libmagic*

/opt/PaperLess/lib/libmagic.a 
 /opt/PaperLess/lib/libmagic.la*  
/opt/PaperLess/lib/libmagic.so@  
/opt/PaperLess/lib/libmagic.so.1@ 
 /opt/PaperLess/lib/libmagic.so.1.0.0*


[/share/CACHEDEV1_DATA/.qpkg/PaperLess/paperless/src] # /opt/PaperLess/bin/python3 test.py
None
None

**Comment by nephaste** [comment]
no more idea ? can it be a problem related to Python 3.7.1 ?

which Python3 version is recommended, i can have a try to cross compile again

**Comment by erikarvstedt** [comment]
Paperless works with all Python versions >= 3.4. (This requirement is due to Django 2.0.)

To help you debugging:
Start with this minimal example:
```
import ctypes.util
print(ctypes.util.find_library('magic'))
```
`LD_LIBRARY_PATH="/my/libpath/:$LD_LIBRARY_PATH" python minimal.py`

and gradually transform it to your current buggy configuration. Then notice at which step the error appears.

**Comment by nephaste** [comment]
thanks Erik...

i create a minimal.py with those lines but it remain the same

export LD_LIBRARY_PATH=/opt/PaperLess/lib:$LD_LIBRARY_PATH
cd /opt/PaperLess/paperless/
export PATH=/opt/PaperLess/bin:$PATH

[/opt/PaperLess/paperless] # which python3
/opt/PaperLess/bin/python3

vi minimal.py (inside your two lines)

[/opt/PaperLess/paperless] # python3 minimal.py
None

**Comment by erikarvstedt** [comment]
Try to make this minimal example work by using your distro's stock Python and libmagic.
Then swap in the corresponding Paperless components bit by bit.

**Comment by nephaste** [comment]
problem there is no python basically in the distro
Python 3.7.1 is cross compiled from source within the Parperless $PREFIX

something probably went bad during cross compilation, and cant find libmagic header... (my opinion)
i am not sure if libmagic is a dependency from Python (optional).. or another Python module

**Comment by nephaste** [comment]
cross compiled all again today taking care to compile libmagic first before python
still no luck... i have really no clue what is wrong...

I will may be have a try with python 3.6.x
