### ISSUE TITLE
Unable to initialise the SQLite database 

### ISSUE THREAD

**Issue by ooii** [danielquinn/paperless#444]
Hi,

I'm trying to run paperless in osx. I followed the bare metal route setup and I'm stuck at step 4 `Initialise the SQLite database`. When I run `./src/manage.py migrate` I have the following result:

```
Traceback (most recent call last):
  File "./src/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/private/tmp/paperless/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "/private/tmp/paperless/venv/lib/python3.7/site-packages/django/core/management/__init__.py", line 347, in execute
    django.setup()
  File "/private/tmp/paperless/venv/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/private/tmp/paperless/venv/lib/python3.7/site-packages/django/apps/registry.py", line 120, in populate
    app_config.ready()
  File "/private/tmp/paperless/src/paperless_tesseract/apps.py", line 12, in ready
    from .signals import ConsumerDeclaration
  File "/private/tmp/paperless/src/paperless_tesseract/signals.py", line 3, in <module>
    from .parsers import RasterisedDocumentParser
  File "/private/tmp/paperless/src/paperless_tesseract/parsers.py", line 15, in <module>
    import pdftotext
ImportError: dlopen(/private/tmp/paperless/venv/lib/python3.7/site-packages/pdftotext.cpython-37m-darwin.so, 2): Symbol not found: __ZN7poppler24set_debug_error_functionEPFvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPvES8_
  Referenced from: /private/tmp/paperless/venv/lib/python3.7/site-packages/pdftotext.cpython-37m-darwin.so
  Expected in: flat namespace
 in /private/tmp/paperless/venv/lib/python3.7/site-packages/pdftotext.cpython-37m-darwin.so
```
I'm running it in a `virtualenv` I had to install `poppler` before the `pip3 install` could be successful for `pdftottext`.

Thanks for your help.

**Comment by danielquinn** [comment]
I have no idea.  This may be something to check with the `pdftotext` project 'cause I've never seen anything like this.
