### ISSUE TITLE
Postgres row index too big

### ISSUE THREAD

**Issue by sammy8806** [danielquinn/paperless#455]
While inserting the first documents I found that postgres tried to make a "simple" index on the `documents_document.content` column which contains the whole imported text from the document.

The problematic line is: `Error:  Size 2944 of row-index is higher than maximum 2712 of index »documents_document_content_aa150741«`

The problem appears if the consumed document has a considerable amount of text in it.

Here is some more info about my environment with some logs:
```
pipenv[27964]: Starting document consumer at /storage/Documents/paperless-scan with inotify
pipenv[27964]: Parsers available: RasterisedDocumentParser
pipenv[27964]: Consuming /storage/Documents/paperless-scan/document0001.pdf
pipenv[27964]: ** Processing: /tmp/paperless/paperless-tnid345_/convert.png
pipenv[27964]: 500x708 pixels, 3x16 bits/pixel, RGB
pipenv[27964]: Input IDAT size = 1447246 bytes
pipenv[27964]: Input file size = 1453164 bytes
pipenv[27964]: Trying:
pipenv[27964]:   zc = 9  zm = 9  zs = 0  f = 0                IDAT size = 1389822
pipenv[27964]:   zc = 9  zm = 8  zs = 0  f = 0                IDAT size = 1386609
pipenv[27964]: [258B blob data]
pipenv[27964]:   zc = 9  zm = 8  zs = 0  f = 1                IDAT size = 1277696
pipenv[27964]: [1.1K blob data]
pipenv[27964]: Selecting parameters:
pipenv[27964]:   zc = 9  zm = 8  zs = 0  f = 1                IDAT size = 1277696
pipenv[27964]: Output file: /tmp/paperless/paperless-tnid345_/optipng.png
pipenv[27964]: Output IDAT size = 1277696 bytes (169550 bytes decrease)
pipenv[27964]: Output file size = 1283086 bytes (170078 bytes = 11.70% decrease)
pipenv[27964]: [pgm_pipe @ 0x559142391800] Stream #0: not enough frames to estimate rate; consider increasing probesize
pipenv[27964]: [image2 @ 0x559142397b80] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
pipenv[27964]: [image2 @ 0x559142397b80] Encoder did not produce proper pts, making some up.
pipenv[27964]: Processing sheet #1: /tmp/paperless/paperless-tnid345_/convert-0000.pnm -> /tmp/paperless/paperless-tnid345_/convert-0000.unpaper.pnm
pipenv[27964]: out of deviation range - NO ROTATING
pipenv[27964]: OCRing the document
pipenv[27964]: Parsing for deu
pipenv[27964]: Detected document date 2018-11-01T00:00:00+00:00 based on string November 2018
pipenv[27964]: Traceback (most recent call last):
pipenv[27964]:   File "/srv/http/.local/share/virtualenvs/src-aT-FNI8A/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
pipenv[27964]:     return self.cursor.execute(sql, params)
pipenv[27964]: psycopg2.OperationalError: FEHLER:  Größe 2944 der Indexzeile überschreitet Maximum 2712 für Index »documents_document_content_aa150741«
pipenv[27964]: HINT:  Werte, die größer sind als 1/3 einer Pufferseite, können nicht indiziert werden.
pipenv[27964]: Erstellen Sie eventuell einen Funktionsindex auf einen MD5-Hash oder verwenden Sie Volltextindizierung.
pipenv[27964]: The above exception was the direct cause of the following exception:
pipenv[27964]: Traceback (most recent call last):
...
pipenv[27964]:   File "/usr/share/webapps/paperless/src/documents/management/commands/document_consumer.py", line 96, in handle
pipenv[27964]:     self.loop_inotify(mail_delta)
pipenv[27964]:   File "/usr/share/webapps/paperless/src/documents/management/commands/document_consumer.py", line 129, in loop_inotify
pipenv[27964]:     self.loop_step(mail_delta)
pipenv[27964]:   File "/usr/share/webapps/paperless/src/documents/management/commands/document_consumer.py", line 121, in loop_step
pipenv[27964]:     self.file_consumer.consume_new_files()
pipenv[27964]:   File "/usr/share/webapps/paperless/src/documents/consumer.py", line 112, in consume_new_files
pipenv[27964]:     if not self.try_consume_file(file):
pipenv[27964]:   File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
pipenv[27964]:     return func(*args, **kwds)
pipenv[27964]:   File "/usr/share/webapps/paperless/src/documents/consumer.py", line 158, in try_consume_file
pipenv[27964]:     date
pipenv[27964]:   File "/usr/share/webapps/paperless/src/documents/consumer.py", line 225, in _store
pipenv[27964]:     storage_type=self.storage_type
pipenv[27964]:   File "/srv/http/.local/share/virtualenvs/src-aT-FNI8A/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
pipenv[27964]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
pipenv[27964]:   File "/srv/http/.local/share/virtualenvs/src-aT-FNI8A/lib/python3.7/site-packages/django/db/models/query.py", line 417, in create
pipenv[27964]:     obj.save(force_insert=True, using=self.db)
pipenv[27964]:   File "/srv/http/.local/share/virtualenvs/src-aT-FNI8A/lib/python3.7/site-packages/django/db/models/base.py", line 729, in save
pipenv[27964]:     force_update=force_update, update_fields=update_fields)
...
pipenv[27964]:   File "/srv/http/.local/share/virtualenvs/src-aT-FNI8A/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
pipenv[27964]:     raise dj_exc_value.with_traceback(traceback) from exc_value
pipenv[27964]:   File "/srv/http/.local/share/virtualenvs/src-aT-FNI8A/lib/python3.7/site-packages/django/db/backends/utils.py", line 85, in _execute
pipenv[27964]:     return self.cursor.execute(sql, params)
pipenv[27964]: django.db.utils.OperationalError: FEHLER:  Größe 2944 der Indexzeile überschreitet Maximum 2712 für Index »documents_document_content_aa150741«
pipenv[27964]: HINT:  Werte, die größer sind als 1/3 einer Pufferseite, können nicht indiziert werden.
pipenv[27964]: Erstellen Sie eventuell einen Funktionsindex auf einen MD5-Hash oder verwenden Sie Volltextindizierung.
systemd[1]: paperless-consumer.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: paperless-consumer.service: Failed with result 'exit-code'.
systemd[1]: paperless-consumer.service: Service RestartSec=100ms expired, scheduling restart.
systemd[1]: paperless-consumer.service: Scheduled restart job, restart counter is at 32.
systemd[1]: Stopped Paperless consumer.
```

**Versions**
- System: `Arch`
- Postgres: `11.1`
- Python: `3.7.1`
- Django: `2.0.9`
- Psycopg2: `2.7.6.1`

**Comment by lociii** [comment]
English error log:

```
paperless_consumer_1   | Traceback (most recent call last):
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
paperless_consumer_1   |     return self.cursor.execute(sql, params)
paperless_consumer_1   | psycopg2.OperationalError: index row size 6176 exceeds maximum 2712 for index "documents_document_content_aa150741"
paperless_consumer_1   | HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
paperless_consumer_1   | Consider a function index of an MD5 hash of the value, or use full text indexing.
paperless_consumer_1   | 
paperless_consumer_1   | 
paperless_consumer_1   | The above exception was the direct cause of the following exception:
paperless_consumer_1   | 
paperless_consumer_1   | Traceback (most recent call last):
paperless_consumer_1   |   File "/usr/src/paperless/src/manage.py", line 11, in <module>
paperless_consumer_1   |     execute_from_command_line(sys.argv)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
paperless_consumer_1   |     utility.execute()
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 365, in execute
paperless_consumer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 288, in run_from_argv
paperless_consumer_1   |     self.execute(*args, **cmd_options)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 335, in execute
paperless_consumer_1   |     output = self.handle(*args, **options)
paperless_consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 96, in handle
paperless_consumer_1   |     self.loop_inotify(mail_delta)
paperless_consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 129, in loop_inotify
paperless_consumer_1   |     self.loop_step(mail_delta)
paperless_consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 121, in loop_step
paperless_consumer_1   |     self.file_consumer.consume_new_files()
paperless_consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 112, in consume_new_files
paperless_consumer_1   |     if not self.try_consume_file(file):
paperless_consumer_1   |   File "/usr/lib/python3.6/contextlib.py", line 52, in inner
paperless_consumer_1   |     return func(*args, **kwds)
paperless_consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 158, in try_consume_file
paperless_consumer_1   |     date
paperless_consumer_1   |   File "/usr/src/paperless/src/documents/consumer.py", line 225, in _store
paperless_consumer_1   |     storage_type=self.storage_type
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
paperless_consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 417, in create
paperless_consumer_1   |     obj.save(force_insert=True, using=self.db)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
paperless_consumer_1   |     force_update=force_update, update_fields=update_fields)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
paperless_consumer_1   |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
paperless_consumer_1   |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
paperless_consumer_1   |     using=using, raw=raw)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
paperless_consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/query.py", line 1128, in _insert
paperless_consumer_1   |     return query.get_compiler(using=using).execute_sql(return_id)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
paperless_consumer_1   |     cursor.execute(sql, params)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
paperless_consumer_1   |     return super().execute(sql, params)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
paperless_consumer_1   |     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
paperless_consumer_1   |     return executor(sql, params, many, context)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
paperless_consumer_1   |     return self.cursor.execute(sql, params)
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
paperless_consumer_1   |     raise dj_exc_value.with_traceback(traceback) from exc_value
paperless_consumer_1   |   File "/usr/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
paperless_consumer_1   |     return self.cursor.execute(sql, params)
paperless_consumer_1   | django.db.utils.OperationalError: index row size 6176 exceeds maximum 2712 for index "documents_document_content_aa150741"
paperless_consumer_1   | HINT:  Values larger than 1/3 of a buffer page cannot be indexed.
paperless_consumer_1   | Consider a function index of an MD5 hash of the value, or use full text indexing.
```

**Comment by HendrikF** [comment]
I have the same problem.

```
Mar 02 01:32:10 paperless systemd[1]: Started Paperless consumer.
Mar 02 01:32:11 paperless python[982]: Starting document consumer at /opt/paperless/chroot/consumption with inotify
Mar 02 01:32:12 paperless python[982]: Parsers available: RasterisedDocumentParser
Mar 02 01:32:12 paperless python[982]: Consuming /opt/paperless/chroot/consumption/Scan0001.pdf
Mar 02 01:32:13 paperless python[982]: ** Processing: /tmp/paperless/paperless-_bvcn6ui/convert.png
Mar 02 01:32:13 paperless python[982]: 500x708 pixels, 4x16 bits/pixel, RGB+alpha
Mar 02 01:32:13 paperless python[982]: Reducing image to 3x16 bits/pixel, RGB
Mar 02 01:32:13 paperless python[982]: Input IDAT size = 1268199 bytes
Mar 02 01:32:13 paperless python[982]: Input file size = 1271353 bytes
Mar 02 01:32:13 paperless python[982]: Trying:
Mar 02 01:32:13 paperless python[982]:   zc = 9  zm = 9  zs = 0  f = 0                IDAT size = 998261
Mar 02 01:32:14 paperless python[982]:   zc = 9  zm = 8  zs = 0  f = 0                IDAT size = 995710
Mar 02 01:32:24 paperless python[982]: [1.4K blob data]
Mar 02 01:32:24 paperless python[982]: Selecting parameters:
Mar 02 01:32:24 paperless python[982]:   zc = 9  zm = 8  zs = 0  f = 0                IDAT size = 995710
Mar 02 01:32:24 paperless python[982]: Output file: /tmp/paperless/paperless-_bvcn6ui/optipng.png
Mar 02 01:32:24 paperless python[982]: Output IDAT size = 995710 bytes (272489 bytes decrease)
Mar 02 01:32:24 paperless python[982]: Output file size = 998408 bytes (272945 bytes = 21.47% decrease)
Mar 02 01:32:55 paperless python[982]: [pgm_pipe @ 0x5622c63eb0a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:32:55 paperless python[982]: [pgm_pipe @ 0x56453e7680a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:32:55 paperless python[982]: [pgm_pipe @ 0x561985c380a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:32:55 paperless python[982]: [pgm_pipe @ 0x5576992cc0a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:32:55 paperless python[982]: [pgm_pipe @ 0x5565ead6e0a0] [pgm_pipe @ 0x5559c4b6e0a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:32:55 paperless python[982]: Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:33:02 paperless python[982]: [image2 @ 0x561985c3b760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:02 paperless python[982]: [image2 @ 0x561985c3b760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:02 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0000.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0000.unpaper.pnm
Mar 02 01:33:02 paperless python[982]: out of deviation range - NO ROTATING
Mar 02 01:33:02 paperless python[982]: [pgm_pipe @ 0x56469853a0a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:33:05 paperless python[982]: [image2 @ 0x56453e76b760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:05 paperless python[982]: [image2 @ 0x56453e76b760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:05 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0008.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0008.unpaper.pnm
Mar 02 01:33:05 paperless python[982]: [image2 @ 0x5559c4b71760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:05 paperless python[982]: [image2 @ 0x5559c4b71760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:05 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0009.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0009.unpaper.pnm
Mar 02 01:33:05 paperless python[982]: [pgm_pipe @ 0x55fbc687c0a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:33:05 paperless python[982]: [pgm_pipe @ 0x55f7b0f790a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:33:05 paperless python[982]: [image2 @ 0x5565ead71760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:05 paperless python[982]: [image2 @ 0x5565ead71760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:05 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0006.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0006.unpaper.pnm
Mar 02 01:33:06 paperless python[982]: [pgm_pipe @ 0x55d788d410a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:33:08 paperless python[982]: [image2 @ 0x5622c63ee760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:08 paperless python[982]: [image2 @ 0x5622c63ee760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:08 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0007.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0007.unpaper.pnm
Mar 02 01:33:08 paperless python[982]: [image2 @ 0x5576992cf760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:08 paperless python[982]: [pgm_pipe @ 0x557c090e20a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:33:08 paperless python[982]: [image2 @ 0x5576992cf760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:08 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0001.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0001.unpaper.pnm
Mar 02 01:33:08 paperless python[982]: [pgm_pipe @ 0x5565341e80a0] Stream #0: not enough frames to estimate rate; consider increasing probesize
Mar 02 01:33:09 paperless python[982]: [image2 @ 0x56469853d760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:09 paperless python[982]: [image2 @ 0x56469853d760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:09 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0002.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0002.unpaper.pnm
Mar 02 01:33:14 paperless python[982]: [image2 @ 0x55fbc687f760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:14 paperless python[982]: [image2 @ 0x55fbc687f760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:14 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0004.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0004.unpaper.pnm
Mar 02 01:33:17 paperless python[982]: [image2 @ 0x557c090e5760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:17 paperless python[982]: [image2 @ 0x557c090e5760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:17 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0011.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0011.unpaper.pnm
Mar 02 01:33:18 paperless python[982]: [image2 @ 0x55d788d44760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:18 paperless python[982]: [image2 @ 0x55f7b0f7c760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:18 paperless python[982]: [image2 @ 0x55d788d44760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:18 paperless python[982]: [image2 @ 0x55f7b0f7c760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:18 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0005.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0005.unpaper.pnm
Mar 02 01:33:18 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0003.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0003.unpaper.pnm
Mar 02 01:33:18 paperless python[982]: [image2 @ 0x5565341eb760] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
Mar 02 01:33:18 paperless python[982]: [image2 @ 0x5565341eb760] Encoder did not produce proper pts, making some up.
Mar 02 01:33:18 paperless python[982]: Processing sheet #1: /tmp/paperless/paperless-_bvcn6ui/convert-0010.pnm -> /tmp/paperless/paperless-_bvcn6ui/convert-0010.unpaper.pnm
Mar 02 01:33:18 paperless python[982]: OCRing the document
Mar 02 01:33:18 paperless python[982]: Parsing for deu
Mar 02 01:33:29 paperless python[982]: Parsing for deu
Mar 02 01:33:49 paperless python[982]: Parsing for deu
Mar 02 01:34:29 paperless python[982]: Detected document date 2019-01-01T00:00:00+01:00 based on string Januar 2019
Mar 02 01:34:29 paperless python[982]: Traceback (most recent call last):
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
Mar 02 01:34:29 paperless python[982]:     return self.cursor.execute(sql, params)
Mar 02 01:34:29 paperless python[982]: psycopg2.OperationalError: index row requires 17616 bytes, maximum size is 8191
Mar 02 01:34:29 paperless python[982]: The above exception was the direct cause of the following exception:
Mar 02 01:34:29 paperless python[982]: Traceback (most recent call last):
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/paperless/src/manage.py", line 11, in <module>
Mar 02 01:34:29 paperless python[982]:     execute_from_command_line(sys.argv)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 371, in execute_from_command_line
Mar 02 01:34:29 paperless python[982]:     utility.execute()
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 365, in execute
Mar 02 01:34:29 paperless python[982]:     self.fetch_command(subcommand).run_from_argv(self.argv)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/core/management/base.py", line 288, in run_from_argv
Mar 02 01:34:29 paperless python[982]:     self.execute(*args, **cmd_options)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/core/management/base.py", line 335, in execute
Mar 02 01:34:29 paperless python[982]:     output = self.handle(*args, **options)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/paperless/src/documents/management/commands/document_consumer.py", line 96, in handle
Mar 02 01:34:29 paperless python[982]:     self.loop_inotify(mail_delta)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/paperless/src/documents/management/commands/document_consumer.py", line 129, in loop_inotify
Mar 02 01:34:29 paperless python[982]:     self.loop_step(mail_delta)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/paperless/src/documents/management/commands/document_consumer.py", line 121, in loop_step
Mar 02 01:34:29 paperless python[982]:     self.file_consumer.consume_new_files()
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/paperless/src/documents/consumer.py", line 112, in consume_new_files
Mar 02 01:34:29 paperless python[982]:     if not self.try_consume_file(file):
Mar 02 01:34:29 paperless python[982]:   File "/usr/lib/python3.5/contextlib.py", line 30, in inner
Mar 02 01:34:29 paperless python[982]:     return func(*args, **kwds)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/paperless/src/documents/consumer.py", line 158, in try_consume_file
Mar 02 01:34:29 paperless python[982]:     date
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/paperless/src/documents/consumer.py", line 225, in _store
Mar 02 01:34:29 paperless python[982]:     storage_type=self.storage_type
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
Mar 02 01:34:29 paperless python[982]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/query.py", line 417, in create
Mar 02 01:34:29 paperless python[982]:     obj.save(force_insert=True, using=self.db)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/base.py", line 729, in save
Mar 02 01:34:29 paperless python[982]:     force_update=force_update, update_fields=update_fields)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/base.py", line 759, in save_base
Mar 02 01:34:29 paperless python[982]:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/base.py", line 842, in _save_table
Mar 02 01:34:29 paperless python[982]:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/base.py", line 880, in _do_insert
Mar 02 01:34:29 paperless python[982]:     using=using, raw=raw)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
Mar 02 01:34:29 paperless python[982]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/query.py", line 1128, in _insert
Mar 02 01:34:29 paperless python[982]:     return query.get_compiler(using=using).execute_sql(return_id)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1285, in execute_sql
Mar 02 01:34:29 paperless python[982]:     cursor.execute(sql, params)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 100, in execute
Mar 02 01:34:29 paperless python[982]:     return super().execute(sql, params)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 68, in execute
Mar 02 01:34:29 paperless python[982]:     return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
Mar 02 01:34:29 paperless python[982]:     return executor(sql, params, many, context)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
Mar 02 01:34:29 paperless python[982]:     return self.cursor.execute(sql, params)
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
Mar 02 01:34:29 paperless python[982]:     raise dj_exc_value.with_traceback(traceback) from exc_value
Mar 02 01:34:29 paperless python[982]:   File "/opt/paperless/venv/lib/python3.5/site-packages/django/db/backends/utils.py", line 85, in _execute
Mar 02 01:34:29 paperless python[982]:     return self.cursor.execute(sql, params)
Mar 02 01:34:29 paperless python[982]: django.db.utils.OperationalError: index row requires 17616 bytes, maximum size is 8191
Mar 02 01:34:30 paperless systemd[1]: paperless-consumer.service: Main process exited, code=exited, status=1/FAILURE
Mar 02 01:34:30 paperless systemd[1]: paperless-consumer.service: Unit entered failed state.
Mar 02 01:34:30 paperless systemd[1]: paperless-consumer.service: Failed with result 'exit-code'.
```

I installed to Postgres by adding these Options to `/etc/paperless.conf`:
```
PAPERLESS_DBNAME=paperless
PAPERLESS_DBUSER=paperless
PAPERLESS_DBPASS=
PAPERLESS_DBHOST=
PAPERLESS_DBPORT=5432
```
```
sudo -u postgres createdb -O paperless -E utf-8 paperless
```

I was able to consume some invoices, which were text based pdfs. This error occurs for scanned pdfs.

"Bare metal" / no Docker install in a VM

Debian Stretch 9.8  
Python 3.5.3  
Paperless `6d8e4ad6b` which is `master` as of 2019-03-02  
Django 2.0.10  
Postgres 9.6.11

Only change to the Python packages is, that after `pip install -r requirements.txt` I uninstalled psycopg2 and installed psycopg2-binary (2.7.7), because psycopg2 logged deprecation warnings saying to do so.

**Comment by HendrikF** [comment]
I was able to work around this issue with these instructions:
https://github.com/the-paperless-project/paperless/issues/397#issuecomment-423815785

You have to delete the indices "documents_document_content_*".
This could lead to longer search times.

```
$ src/manage.py dbshell
paperless=> \d documents_document # to see how the indices are called exactly
DROP INDEX documents_document_content_aa150741;
DROP INDEX documents_document_content_aa150741_like;
```

A general solution to use Postgres would be nice though.
