### ISSUE TITLE
Consumer crashes when reading files

### ISSUE THREAD

**Issue by jcpsantiago** [danielquinn/paperless#61]
Documents were scanned with Simple Scan in Arch Linux with a Bare Metal "install". The webserver is running fine. I edited the settings.py as per the setup instructions. OCR_THREADS is set to "2" (I'm running an i7).

I don't know much about python, so please tell me what other infos I can provide.

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/mariachi/bin/paperless/src/documents/consumer.py", line 237, in image_to_string
    ocr = pyocr.get_available_tools()[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/mariachi/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/mariachi/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/mariachi/.local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/mariachi/.local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/mariachi/bin/paperless/src/documents/management/commands/document_consumer.py", line 49, in handle
    self.loop()
  File "/home/mariachi/bin/paperless/src/documents/management/commands/document_consumer.py", line 59, in loop
    self.file_consumer.consume()
  File "/home/mariachi/bin/paperless/src/documents/consumer.py", line 113, in consume
    text = self._get_ocr(pngs)
  File "/home/mariachi/bin/paperless/src/documents/consumer.py", line 173, in _get_ocr
    raw_text = self._ocr([pngs[middle]], self.DEFAULT_OCR_LANGUAGE)
  File "/home/mariachi/bin/paperless/src/documents/consumer.py", line 229, in _ocr
    self.image_to_string, itertools.product(pngs, [lang]))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
IndexError: list index out of range

```

**Comment by danielquinn** [comment]
It's hard to tell without looking at the document itself for my own testing, but it might be something as simple as the number of pages, so I'll give it a test when I get home tonight.  In the mean time, can you confirm that:

* You have tesseract and ImageMagick installed
* ImageMagick was compiled with PDF support (on some systems this means that ghostscript wasn't installed, which can cause strange things)
* All documents you're attempting to import fail, or if some succeed, what differentiates the working PDFs from the failing ones?  Given the nature of this traceback, I'm curious about page quantities specifically.
* You're running Python 3.

If you're willing to share the document, that would help me diagnose the problem, but if not, that doesn't mean I won't try to fix it, so don't worry :-)

**Comment by jcpsantiago** [comment]
it seems I didn't have tesseract installed. my bad. ;)

**Comment by danielquinn** [comment]
No problem!  I'm glad it was an easy fix.

If you think that the documentation can be amended to make sure this doesn't happen to others, please feel free to let me know or issue a PR of your own!
