### ISSUE TITLE
Thumbnail migration fails if scratch-dir doesn't exist

### ISSUE THREAD

**Issue by pitkley** [danielquinn/paperless#76]
```console
$ docker-compose run --rm webserver migrate
Mapping UID and GID for paperless:paperless to 1002:1002
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, documents, sessions
Running migrations:
  Applying documents.0012_auto_20160305_0040...

  This is a one-time only migration to generate thumbnails for all of your
  documents so that future UIs will have something to work with.  If you have
  a lot of documents though, this may take a while, so a coffee break may be
  in order.

    * Generating a thumbnail for 0000001.pdf.gpg
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 121, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 198, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 123, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/operations/special.py", line 183, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/src/paperless/src/documents/migrations/0012_auto_20160305_0040.py", line 67, in move_documents_and_create_thumbnails
    prefix="paperless", dir=settings.SCRATCH_DIR)
  File "/usr/local/lib/python3.5/tempfile.py", line 368, in mkdtemp
    _os.mkdir(file, 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/paperless/paperlessfpq1s0m5'
```

While I have only tested it within Docker, I'm fairly sure that this happens on bare-metal and Vagrant too since the scratch-directory get's created only [in the consumer](https://github.com/danielquinn/paperless/blob/fb36a49c2681aa5362e30f266e85c89565a310c3/src/documents/consumer.py#L75-L78). I assume that those lines have to be in the migration too.

**Comment by danielquinn** [comment]
You know, I actually thought to test it for a brand new setup, but it never occurred to me to nuke my temp dirs before hand.  Thanks for that.
