### ISSUE TITLE
Click requirement

### ISSUE THREAD

**Issue by plaindocs** [danielquinn/paperless#78]
I needed to `pip3 install click` as well as other requirements.

**Comment by danielquinn** [comment]
`click` is a dependency for `python-dotenv` which is listed in `requirements.txt`.  Is it possible that something went wrong during your installation and all of the dependencies didn't install right?  If you uninstall click and python-dotenv and then reinstall python-dotenv, it should pull click in automatically (at least it did for me):

```
$ pip uninstall click
Uninstalling click-6.3:
...
Proceed (y/n)? y
  Successfully uninstalled click-6.3

$ manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 14, in <module>
    if not settings.PASSPHRASE:
  File "/home/daniel/.virtualenvs/paperless/lib/python3.4/site-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/home/daniel/.virtualenvs/paperless/lib/python3.4/site-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/daniel/.virtualenvs/paperless/lib/python3.4/site-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/daniel/.virtualenvs/paperless/lib64/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/daniel/Projects/paperless/src/paperless/settings.py", line 15, in <module>
    from dotenv import load_dotenv
  File "/home/daniel/.virtualenvs/paperless/lib/python3.4/site-packages/dotenv.py", line 10, in <module>
    import click
ImportError: No module named 'click'

$ pip uninstall python-dotenv
Uninstalling python-dotenv-0.3.0:
...
Proceed (y/n)? y
  Successfully uninstalled python-dotenv-0.3.0

$ pip install python-dotenv
Collecting python-dotenv
  Using cached python_dotenv-0.3.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): ordereddict in /home/daniel/.virtualenvs/paperless/lib/python3.4/site-packages (from python-dotenv)
Collecting click>=5.0 (from python-dotenv)
  Using cached click-6.3-py2.py3-none-any.whl
Installing collected packages: click, python-dotenv
Successfully installed click-6.3 python-dotenv-0.3.0

$ pip freeze
click==6.3
```

I don't think I can fix that. If `click` doesn't install as part of python-dotenv for you, that's probably a problem for upstream.
